### ISSUE TITLE
Shift to Wikipedia-compatible license

### ISSUE THREAD

**Issue by metasj** [nytimes/covid-19-data#12]
This is important, thank you for posting it.
(Do you have related line list data as well?)

Echoing #10 but more specifically: please change the license to a CC license that would let this data be integrated more easily into Wikipedia. WP already has crowdsourced versions of most of this data, with sources, but both projects would benefit from a more thorough synchronization.

The ideal license for data is **CC-0**, which matches the license of government data (including that in your sources.) That would let this dataset be part of the [public](https://www.wikidata.org/wiki/Wikidata:Licensing) [knowledge graph](https://wikidata.org) (**Wikidata**), where every revision of each data point can have one or more sources -- important for tracking some of the important nuances here.  Please make this happen!

**Comment by samboy** [comment]
I don’t think we need to worry too much about the license: Basic facts can *not* be copyrighted; there is [case law saying no one can copyright this data](https://en.wikipedia.org/wiki/Feist_Publications,_Inc.,_v._Rural_Telephone_Service_Co.)

**Comment by metasj** [comment]
Absolutely right, and anyone can use individual data points without worrying.

But using a CC-0 license makes it _faster_ and _less uncertain_ for people to synchronize large datasets with one another.  Explicitly using an incompatible license leads others to replicate the work and duplicate effort.

**Comment by cipriancraciun** [comment]
I second @metasj regarding those that try to build-upon these values.  For example I've started one week ago to re-process and augment the JHU dataset, and now I have integrated the NY Times one as well.

Unfortunately I'm not sure how should I license my derived files, because neither JHU nor NY specify an actual proper license...

**Comment by kaldari** [comment]
@metasj is right. While data itself can't be copyrighted, datasets can be (as long as there is human involvement in the selection and presentation of the data). It would be really useful if this data were released under a Creative Commons license so that the legal terms were more clear (and perhaps less restrictive than the current terms).

**Comment by albertsun** [comment]
@metasj today we've updated our README.md to clarify that we consider the LICENSE we posted this under to be co-extensive with and equivalent to the CC BY-NC license. Hope that helps.

As for line list data, we may consider making available some version of what we have (which does not cover demographic data for all cases, especially now with so many more) to qualified scientists who ask for it for a specific research project, but we will not be releasing that publicly.

**Comment by metasj** [comment]
Thanks for the update, which I didn't see at the time; that is helpful. 
 
I hope you can set up some embargo process where all non-PII COVID data is released under CC-0 after some period, to match the license of the government data + support future epidemiology.
