### ISSUE TITLE
Washington DC Missing Data for March 29

### ISSUE THREAD

**Issue by link2matt** [nytimes/covid-19-data#124]
You are missing the data for Washington DC on March 29.   
401 cumulative cases were reported on 3/29
4 additional deaths were reported on 3/29, bringing the death total to 9. 
Here's the link for a press release for that day with these figures:
https://coronavirus.dc.gov/release/coronavirus-data-update-march-29

Thanks you for providing this data.

**Comment by albertsun** [comment]
So, the numbers for D.C. are a little tricky.

Each morning, D.C. reports the number of cases from the previous day. Because our counts are based on when cases are announced, to be consistent with other localities, our numbers for D.C. reflect when we got the updated numbers even though D.C. attributes that to the day before.

In late March there was some inconsistency in when the updates were posted live and when w incorporated them into our data set, which is why our counts may be off by a day or not off by a day from when D.C. shows their cases. We are looking into how to do more historical adjustments like this and will update if we can.
