### ISSUE TITLE
where is the age n previous medical condition in the database

### ISSUE THREAD

**Issue by aminnagpure** [nytimes/covid-19-data#125]
iam trying to build a prediction model, pls update age, n previous medical condition in database otherwise its worthless

**Comment by rcweinbe** [comment]
Worthless? Having time series data on the virus by county/state is not "worthless".  Try to be respectful.  If you have this data (which by the way is highly protected by HIPAA), feel free to add to this dataset yourself rather than expect others to magically have it.  Otherwise, please don't put down others that have done us a great service by compiling useful summary data.

**Comment by albertsun** [comment]
For this data release we focused on consistent, nationwide county-level data for cases and deaths. Most other data about Covid-19 is not available consistently at the county level.

More states are starting to release that demographic information for their cases at the state level and local levels. There are other efforts to collect that data, which we hope will improve over time.

**Comment by aminnagpure** [comment]
ok but the data missing with age, previous medical condition is not very useful in building prediction models, all hospitals keeps records in computers, all they just need to publish on the internet, that will bring more transparency and will help us build models
