### ISSUE TITLE
Numbers for counties vs states

### ISSUE THREAD

**Issue by rwarner67** [nytimes/covid-19-data#129]
Hello.  I did a manual check of the numbers for Virginia from the states csv to a total number of deaths in for the counties for Virginia in the counties csv.  They do not match.  I also checked the numbers for Maryland.  They are off.  Does anyone have a reason for this?

**Comment by fullersr** [comment]
This may be related.   I read in the St. Louis Post Dispatch that the reporting procedures are not very standardized and so local numbers for STL-city (which is a county) are higher than state-reported numbers.

**Comment by rwarner67** [comment]
Ok.  But with the counties reporting one number who is adding to the mix for the states?  Totally messed up.  I fear there is also excess mortality included and this makes it worse.  We are making crazy assumptions from these reportings.  Do you know who is gathering these numbers for the csv(s)?

**Comment by rwarner67** [comment]
The numbers from the NY times are good.  The csv for the counties is off.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ghe2014** [comment]
The sum of all counties (cases/deaths) for 4/4, you have 310807/8505.  But the sum of all states is (311536/8499).  Quite a difference.

**Comment by PoojaBhansali** [comment]
Hello,

Yes there is an difference between them but minimal, as I can see the difference of 5-10 numbers because in countries.csv files numbers are considered by states by county and in states.csv it considered by only states. 

Datasets_Countries_unique = Datasets_Countries[Datasets_Countries['state'] == 'California']
Datasets_Countries_unique['deaths'].sum()
OUTPUT: 2521

Datasets_States_unique = Datasets_States[Datasets_States['state'] == 'California']
Datasets_States_unique['deaths'].sum()
OUTPUT: 2513

I check couple of states, difference is small and I also confirmed with Pivot table, I just found the reasons of allocation based on county.

Thanks,
Pooja

**Comment by albertsun** [comment]
State and county government reporting of cases are not always consistent. There may be differences in how these entities count residents of other states being treated in one state, residents of one county being treated in another, or the timeframe in which cases are reported. We’ve tried our best to reconcile as many of these differences as possible, but have not been able to do so in all cases.
