### ISSUE TITLE
Include the stay at home/safer at home data

### ISSUE THREAD

**Issue by mhines-usgs** [nytimes/covid-19-data#13]
There are separate NYTimes datasets supporting a graphic/map about where people have been asked to stay home, can you tie that into this dataset at the state and/or county level?

https://www.nytimes.com/interactive/2020/us/coronavirus-stay-at-home-order.html

**Comment by albertsun** [comment]
Thank you for the suggestion. We do expect that doing analysis comparing with that would be useful and interesting. However, since people may want to combine that data in different ways or even with other additional data, we do not have any current plans to provide that data in an additional format.

**Comment by mhines-usgs** [comment]
@albertsun bummer. Is that data available anywhere here in source control? I tweeted at one of the authors but did not hear back.
