### ISSUE TITLE
Data for NYC changed for 4/6 and exceptionally high for 4/7

### ISSUE THREAD

**Issue by isrsal** [nytimes/covid-19-data#151]
Deaths for 4/6 was previously set to 2738 and changed to 3485. Deaths for 4/7 is reported as 4009. These numbers are much higher than previous trend. Does it include NYS or we're actually seeing such a spike in NYC?
These (updated) numbers would represent a NYC deaths toll of 1013 on 4/6 and 524 on 4/7. Past days were in the 200-300 range.

**Comment by albertsun** [comment]
Hi @isrsal, we added a note about this in the README as well but understandably most people are not seeing that.

On 4/6, New York State started releasing county level death counts and we switched over from using deaths reported by New York City to deaths reported by New York State (for New York City). We think this is more consistent with the rest of our data, since we've been using case counts from New York State all along.

Because of their different reporting methodologies this led to a big spike in the reported number. We're trying to understand if there really was a spike in deaths then or not and will continue to revise our data there as we find out more.

**Comment by isrsal** [comment]
@albertsun thank you for clarifying. The new (state reported numbers) do not match the us-states.csv data though.
NY state reported deaths (us-states.csv) is 597 for 4/6 and 805 for 4/7, while NYC reported deaths alone (us-counties.csv) is 1013 for 4/6 and 524 for 4/7.

**Comment by albertsun** [comment]
Yes, while it doesn't make sense that NYC would report more deaths in a single day than New York state, this is a one day statistical anomaly to get us onto what we think is the more accurate reporting path. There were not really 1016 new deaths no 4/6, some of those deaths would actually have taken place before that, we just don't currently know when. We're working on getting that information though.

Cuomo's 731 number for Monday was announced on 4/7 so we are reflecting it in our data for 4/7. That day we have 805 new deaths as we're actually getting some counts from other counties and the Bureau of Prisons who have released their counts in advance of the states.
