### ISSUE TITLE
Ulster County NY Date for 4.8.20

### ISSUE THREAD

**Issue by alicat418** [nytimes/covid-19-data#156]
FIPS 36111.  Cumulative death count is showing "2" for 4.8.20.  It was ""5" on 4.7.20.  Can you explain why it has dropped?  I think this is wrong.  Other sources I have looked online are showing 6.  Could the 2 be a the delta in error.

BTW - fantastic job with this sharing of data.

**Comment by alicat418** [comment]
On here:

https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/

Ulster is up to 6 today.  sorry about my math error above!!  just trying to work out what the "2" is!

**Comment by albertsun** [comment]
Hi @alicat418 we're showing 2 and not 6 because as of 4/8 we've switched over our New York data from reporting deaths based on place of residence to place of fatality, a new data breakout that New York state has started to provide. We haven't revised the historical data yet but are working to do that.

**Comment by alicat418** [comment]
Thanks Albert.  I will wait for that revision then.
