### ISSUE TITLE
Corrupt entries in county dataset

### ISSUE THREAD

**Issue by aebrahim** [nytimes/covid-19-data#165]
There are 687 rows with invalid or missing FIPS ids which seem to be corrupted entries as of 2020-04-12.

See https://gist.github.com/aebrahim/3a627a56a1510f8ed4d4f89fa5b874b2 for details

**Comment by albertsun** [comment]
@aebrahim yes, there are rows for cases of "Unknown" county and merged geographies like New York City that do not map to a single county FIPS code. In those cases we've left the FIPS code field blank.

**Comment by aebrahim** [comment]
Thanks for clarifying @albertsun.

So making sure I understand:  There is no disambiguation within New York City by county - the cases are all in one single pool for all 5 counties, which means it can't be assigned to a FIPS code. Would it be reasonable for someone analyzing the data to then break the NYC bucket down proportionally to each county [proportional by population](https://github.com/hikmahealth/covid19countymap/blob/master/notebooks/NYT_cases_export.ipynb)?

With respect to "Unknown county", for example, "Unknown County, Rhode Island" - is it a case which cannot be localized to one of the 5 counties in the state, but is included in the overall state total?

Thanks for your time, and for all the work on this awesome dataset. Please feel free to close the bug!

**Comment by albertsun** [comment]
I couldn't advise you on how to do any particular analysis. Every data set and method is going to have its own shortcomings.

For NYC, the different boroughs have different numbers of cases per capita. There _is_ more detailed NYC data out there released by NYCDOHMH, but the collection methodology isn't consistent with the rest of the country which is why we haven't integrated that data yet.

And for Rhode Island (and most states), that is correct. The Unknown County cases are ones where the state has not ascertained which county the case has been assigned to yet.
