### ISSUE TITLE
FEATURE Request - Add fields necessary for evaluating rebound

### ISSUE THREAD

**Issue by SCHarris76** [nytimes/covid-19-data#197]
Please plan to include county-level data that will inform steps taken to reduce social distancing. This will greatly facilitate development of algorithms and visualizations intended to identify trends in cases and deaths as social distancing is relaxed progressively over time. Need to adopt some standard coding for various stages/aspects of reduction so patterns in cases/deaths can be tracked over time relative to easing of restrictions.

PS: This 'issue' is not similar to any of the prior 'issues' flagged as being similar...

**Comment by daveroush** [comment]
This is a great idea.  It should also include total tests and it would be good to have the granularity of the data down to the zip code level

**Comment by ArleneMaps** [comment]
I agree with Dave but my state (Vermont) refuses to release town by town data, which is the zip code.  They think it's some sort of privacy issue.

**Comment by daveroush** [comment]
Our State is publishing zip code data.  They felt it was fine as far as privacy goes.  Here is our state dashboard as an example (click on the zip code radio button)

 

https://cvprovider.nmhealth.org/public-dashboard.html

**Comment by SarahEGood** [comment]
This is a great idea! I was already working on a project that was essentially doing the same for the county I live in, but am not at the point where I could factor that into a model myself.

**Comment by tiffehr** [comment]
This thread seems to be changing what is requested, since April.  We provide per-county data at this point, though perhaps when the issue was originally opened we did not yet have it in full.  

Reading this now in July, it seems like it is requesting we collect reopening criteria, which presents many challenges and is beyond our scope.

Please comment if I'm misunderstanding the requests.  I'd recommend kicking off a new Issue, if so.
