### ISSUE TITLE
Santa Clara, CA first death 2/6

### ISSUE THREAD

**Issue by sbulen** [nytimes/covid-19-data#206]
It may take a while for this to trickle thru the local govt reporting:
https://www.axios.com/first-us-coronavirus-death-earlier-autopsy-dbc72f86-30ed-47e5-b5d8-6811643f9853.html

Thanks for the outstanding work.

**Comment by sbulen** [comment]
If the data is based on reported date, not date of death, this will never be reflected in the Santa Clara figures, correct?  If so, this should be closed out.

**Comment by christianpeel** [comment]
An announcement about this death is available on the Santa Clara County [public health department site](https://www.sccgov.org/sites/covid19/Pages/press-release-04-21-20-early.aspx).  Since you've fixed other data retrospectively, it seems like this would be a good change to make.

On a related note, the Santa Clara County Public Health department now shows on their [site](https://www.sccgov.org/sites/covid19/Pages/dashboard.aspx#cases) the number of cases by specimen collection date. Specifically see the "New Specimens by Collection Date" graph.  I'd be happy to make a PR updating this data

**Comment by albertsun** [comment]
We do think that it would be useful to have these earlier deaths represented and we're seeing more and more places release historical data on cases that would allow this data to be revised retroactively. However we haven't figured out the right method to do that yet. There doesn't yet seem to be a broad enough consistent standard on which date to use and how to report it - whether it is symptom onset, specimen collection, positive lab result or something else.
