### ISSUE TITLE
Pennsylvania decremented data . . .

### ISSUE THREAD

**Issue by fbsolo** [nytimes/covid-19-data#221]
2020-04-22 | Pennsylvania | 42 | 36763 | **1720**
2020-04-23 | Pennsylvania | 42 | 38334 | **1713**

**Comment by albertsun** [comment]
Please see the README for this. Pennsylvania has been somewhat inconsistent in how they report probable (not lab-confirmed Covid-19 deaths). For 4/21 and 4/22 they included probable deaths in their total and then on 4/23 they took them out again, which is why the total drops. We're hoping to have a better solution for distinguishing those two case types in the future.
