### ISSUE TITLE
Montana inconsistent data.

### ISSUE THREAD

**Issue by JeremyGrossMT** [nytimes/covid-19-data#229]
I have found many data inconsistent data across many counties.  For now I want highlight Montana.  I'm using the us-counties.csv file.   Note the following from the file list as of 4/26/2020:

4/4/2020 | Toole | Montana | 30101 | 15 | 3
4/5/2020 | Toole | Montana | 30101 | 16 | 3
4/6/2020 | Toole | Montana | 30101 | 15 | 3

The cases goes up on the 4/5/2020 to 16 then on the 4/6/2020 down to 15.  When I try using this data in a chart I get inconsistent results. See the screenshot below. 

![Capture](https://user-images.githubusercontent.com/31456090/80328521-ce3f8880-87fc-11ea-8111-4d283583eff0.PNG)

I have found others for Montana with the same inconsistent:

4/9/2020 | Deer Lodge | Montana | 30023 | 4 | 0

4/9/2020 | Lake | Montana | 30047 | 6 | 0

4/1/2020 | Lewis and Clark | Montana | 30049 | 14 | 0

4/8/2020 | Madison | Montana | 30057 | 9 | 1

4/16/2020 | Musselshell | Montana | 30065 | 3 | 0

I was going write code to not display these dates but, it would better if the these data can be fixed.
I am very grateful to New York Times for providing this data publicly.  I just want to make the data better.

Thank you

**Comment by albertsun** [comment]
@JeremyGrossMT these cases all seem to be cases where the state first reported a higher number of cases for a particular county and then later revised the number downward after further investigation. In these cases the state could be reassigning the case to a different county or even to a different state or simply removing one. We aren't always able to reconcile this data to find what the "right" count is for each date and so are leaving instances of declining case counts in the data rather than attempting to guess at what they would be.
