### ISSUE TITLE
Georgia Data for 2020-04-12 shows a decease in cases.

### ISSUE THREAD

**Issue by jojid** [nytimes/covid-19-data#241]
I see:   
 day     |  state  | fips | cases | deaths 
------------+---------+------+-------+--------
 2020-04-10 | Georgia |   13 | 11859 |    425
 2020-04-11 | Georgia |   13 | 12261 |    432
 2020-04-12 | Georgia |   13 | 12103 |    438
 2020-04-13 | Georgia |   13 | 13125 |    479

So we get a negative number when we take first differences to compute daily numbers. 
George

**Comment by philipmnelson** [comment]
It could be due to updated totals from the Georgia Department Of Public Health. [The DPH has a chart of their cumulative numbers if you want that.](https://dph.georgia.gov/covid-19-daily-status-report)

**Comment by albertsun** [comment]
Hi @jojid, if you take a look at the README you'll see a note about this.

On April 12th, Georgia added a new category for their cases for "Non-Georgia Resident". We started excluding those several hundred cases from our total (since they are likely also being counted in their state of residence) which led to the one day drop.

The Georgia DPH chart does have historic cumulative numbers as well, but you should note in comparing those that they are based on date of symptom onset, not date of case announcement as our data set is, and therefore the curve will look like it is decreasing in recent dates due to not-yet-reported cases.

**Comment by jojid** [comment]
Georgia
Starting April 12th, our case count excludes cases labeled by the state as "Non-Georgia Resident" leading to a one day drop in cases. These cases were previously included as cases with "Unknown" county.
Sorry for bothering you all...
