### ISSUE TITLE
How are people that have recovered from Covid-19 infections represented in the data? Do the daily totals represent cumulative infections or active infections?

### ISSUE THREAD

**Issue by murrayt136** [nytimes/covid-19-data#248]
### Do you think there is an error in the data?
Please submit a Data Issue so it can be easily routed to the correct people.

### Do you have a question about the LICENSE or permission to use this data?
Please email us at covid-data@nytimes.com

### Your question
Please check to make sure your question is not answered in the README. It may have been updated since you first read it.

**Comment by lwaananenjones** [comment]
The daily totals are cumulative. The number of people who have recovered is not represented in the data at this time because it is not reliably available. Some states have started to published the number of recovered patients by county, but most have not yet, and there are various ways to define and count who has recovered.

**Comment by jdkromkowski** [comment]
"Recoved" seems to be here with the caveats of definitional problems. https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data
