### ISSUE TITLE
Deaths are per day, right?   

### ISSUE THREAD

**Issue by harley164** [nytimes/covid-19-data#25]
I saw in the readme there was cumulative, but it has to be per day, right?

**Comment by codypiersall** [comment]
It's the cumulative number of deaths in the county as of the date in the same row.  So each county will have multiple entries, one per day.

**Comment by ronaldgbennett** [comment]
Here is a chart showing the cumulative deaths per county per day beginning from the first reported death:

![Deaths by County](https://user-images.githubusercontent.com/62771947/77797745-d904d300-702e-11ea-9da1-aa8823c64e59.jpg)

**Comment by ronaldgbennett** [comment]
Here is a more complete chart including the top twelve worst counties, all normalized to the first reported death.  Since these are cumulative, the charts never go down, what we are looking for is for them to flatten out and stop increasing as you see in similar charts for China.

![Deaths by County](https://user-images.githubusercontent.com/62771947/77807478-2d1ab200-7045-11ea-9ef2-ba3407a47596.jpg)

**Comment by harley164** [comment]
what i means was that to figure out the total deaths per day you have to subtract from the day before.

The number in the death column for that particular day represents complete total deaths

**Comment by ronaldgbennett** [comment]
Yes, that is correct.  To get the number of deaths for each day, subtract the total from the day before.
