### ISSUE TITLE
Data Issue:  Raleigh County, WV - Total cases decreasing

### ISSUE THREAD

**Issue by jmcparland** [nytimes/covid-19-data#256]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Raleigh County, WV, shows an increase, _then a decrease_ in cases. Is this expected behavior? I searched "issues" with "West Virginia" and I searched the git log, but saw no references to "WV" or "West Virginia" since March 30.

sqlite> select date, cases, deaths from counties where state='West Virginia' and county='Raleigh' and date > '2020-04-25';
date        cases       deaths    
===== ===== =====
2020-04-26  8           0         
2020-04-27  8           0         
2020-04-28  8           0         
2020-04-29  8           0         
2020-04-30  8           0         
2020-05-01  9           0         
2020-05-02  10          0         
2020-05-03  11          0         
2020-05-04  10          0         
2020-05-05  9           0         
sqlite>

**Comment by lwaananenjones** [comment]
These numbers accurately reflect the data West Virginia published each day. Since each case is assigned to the patient's county of residence, occasional decreases like this are fairly common as cases are investigated. West Virginia maintains twice-daily press releases that acknowledge these adjustments. For instance, the 5/4 5 p.m. update says: 

> As case surveillance continues at the local health department level, it may reveal that those tested in a certain county may not be a resident of that county, or even the state as an individual in question may have crossed the state border to be tested.  Such is the case of Mineral, Raleigh, and Wood counties in this report.

https://dhhr.wv.gov/News/2020/Pages/COVID-19-Daily-Update-5-4-2020---5-PM.aspx

Since we don't know exactly how those cases are adjusted, we are leaving instances of declining case counts in the data for now rather than attempting to guess how cases were redistributed.

**Comment by jmcparland** [comment]
Acknowledged and appreciate the response ~ as well as the team's work wrangling all this data. Thanks!
