### ISSUE TITLE
Data Issue: 5/6 New York City stats deviation from norm seem quite excessive 

### ISSUE THREAD

**Issue by bobket45** [nytimes/covid-19-data#261]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources.

**Comment by ddenenberg71** [comment]
It is explained here: https://github.com/nytimes/covid-19-data

**Comment by jrminter** [comment]
Please - if you are going to add the nebulous "probable deaths" do it as an additonal column in the data set so we have both metrics

**Comment by darrinhomme** [comment]
> Please - if you are going to add the nebulous "probable deaths" do it as an additional column in the data set so we have both metrics

At a minimum, don't pile old data into one day. Wait until you have the details.

**Comment by trajanmcgill** [comment]
As someone with an actively used visualization based on this data, one oriented toward trying to identify hotspots visually, I concur that adding as a separate field if possible would be a much preferable way to go. One really big reason is that neighboring jurisdictions reporting two very different facts will make one's status look entirely out of proper proportion to the other. I would rather have the ability to display "unknown" for the places where one or the other metric is unknown, so users know and can choose what they are looking at. With a "confirmed" column and a "probable" or "probable plus confirmed" column, with null values indicating where one or the other of those things is not available, those of us mapping this data would have a lot more ability to ensure users get as accurate as possible an understanding of what they are seeing. Thanks.

**Comment by MichaelGriebe** [comment]
As someone that has been building a model estimating the effect of social distancing and masks on transmission rates, I agree, it would be great if the columns were separated (one for "confirmed" and the other for "probable"), or however you want to do it.  I can subtract it myself if I know how many fall under the new definition.

**Comment by sbulen** [comment]
_The massive spike in deaths isn't even depicted on the NYT site, that is supposed to be driven by this data:_
https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html#states

The jump of New York City deaths by 5600+ overnight is the outlier.  No rolling average:
![image](https://user-images.githubusercontent.com/23568484/81346567-56305880-906f-11ea-95e5-947552a930f4.png)

New deaths.  No rolling average:
![image](https://user-images.githubusercontent.com/23568484/81346434-1e291580-906f-11ea-9eed-85b00d4e8fee.png)

**Comment by albertsun** [comment]
Hi folks, apologies for this. We realize a big one day spike like this is not great for anyone.

Unfortunately, a change over in our internal data collection and processing system meant we had to roll this out today. And we were left with either creating a change over like this with one day spikes in certain areas, or potentially introducing many many revisions to past days' data with potential inaccuracies then, or not publishing updated data. We chose to break the data on May 6th.

We are working as fast as we can and plan both to revise upwards the number of NYC deaths on past day's to smooth out this spike, and to add more detailed data showing confirmed and probable cases separately.

**Comment by Mopholo** [comment]
Can you point us to this new way of doing things, this seems very weird to suddenly uncover new all these new deaths. I would like to see where this is coming from and an explanation of it if you have links.

Can you also tell us which areas are problematic as of now? 

Yes it's irritating, but at least your guys data, up to know, has not been riddled with massive problems like other datasets I have seen, so kudos for that.

**Comment by albertsun** [comment]
To add a little more detail:

Our goal is to have separate columns for confirmed, probable and total cases, following the definition for probable put forward by the [Council of State and Territorial Epidemiologists](https://cdn.ymaws.com/www.cste.org/resource/resmgr/2020ps/Interim-20-ID-01_COVID-19.pdf) which more places are adopting. However the adoption has proceeded at different rates and not all places have always used the same definition, or even made it clear what the numbers they are publishing represent. And because many of our state and national level figures are adjusted based or summed based on county level reports, we are now running into issues summing numbers with different definitions.

Some, but not all of these inconsistencies are in the Geographic Exceptions section of the README already. It's a quickly changing situation and we have not always been able to keep up.

We'd like to be sure that we are following the definition we have for cases and deaths as closely as possible but that's going to take more historical research going back to determine when the places we've been gathering data from have changed definitions.

**Comment by jrminter** [comment]
Thank you for a helpful explanation.

**Comment by albertsun** [comment]
We've posted a more extensive explanation of this change here: https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md

**Comment by albertsun** [comment]
As of yesterday's update there is no longer a large single day increase in deaths.
