### ISSUE TITLE
Data Issue:  NJ case counts 7-day moving average

### ISSUE THREAD

**Issue by avarakin** [nytimes/covid-19-data#271]
### Describe the issue:
Looking at NJ cases counts, I feel that 7 day average is reported about 30% higher than it should be based on daily stats. Same seems to happen for NY too.
Here is the page I am referring to:
https://www.nytimes.com/interactive/2020/us/new-jersey-coronavirus-cases.html

**Comment by albertsun** [comment]
Hi @avarakin, I'm not sure what you mean by what it "should be". Perhaps you are simply using a different method for calculating the moving average?

**Comment by gwhammett** [comment]
I think the explanation is that you are intuitively doing a centered smoothing of the data, taking an average of data from 3 days before through 3 days after a given day.  The Times plots are doing a non-centered "simple moving average" of the previous 7 days.  This means that during a time when the cases are dropping each day, the 7-day average will be higher on average than the cases on a particular day.  A centered smoothing method is essentially a more accurate method (and is more widely used in science and engineering) but it is bit harder to explain and it can't be directly applied to the most recent 3 data points, because that would require knowing the future.  A simple moving average is more widely used in finance.  For more details, see https://en.wikipedia.org/wiki/Moving_average.

You can check the curves by manually averaging 7 days of data and verify it is working as advertised as a simple moving average of the past 7 days.

My suggestion is that this issue can be marked as resolved.
