### ISSUE TITLE
Enhancement: Convert all CSV to JSON and hold both CSV and JSON

### ISSUE THREAD

**Issue by NotMoni** [nytimes/covid-19-data#273]
### Describe the feature you would like to see
Covert the CSV to JSON for JSON usage too.

**Comment by albertsun** [comment]
Hi, in order to keep the number of files we have to maintain to a minimum, we're not going to provide the data in other formats. There are many ways to convert from CSV to JSON. Personally I'm fond of [d3-csv](http://learnjsdata.com/read_data.html) if you like javascript or [csvkit](https://csvkit.readthedocs.io/en/1.0.5/scripts/csvjson.html) on the command line or in Python. There are many others though.
