### ISSUE TITLE
Data Issue:  Georgia DPH state-wide figures

### ISSUE THREAD

**Issue by mcgeedan** [nytimes/covid-19-data#274]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A lot of misinformation on Georgia and the NYTimes website seems to be helping to feed this confusion:

NYTimes:  Total Cases 33,866
Google and GA DPH:  35,427

According to daily counts, there are days of difference.  Is the lag for NYTimes that large?  Is there another reason for so significant a difference?

**Comment by albertsun** [comment]
Hi @mcgeedan,

Our number is lower than the Georgia DPH total number because we are excluding the number of Non-Georgia Resident's that they include. We believe that due to data sharing between state health departments the bulk of those 1,592 cases are also being counted in other states, and so for us to include them in Georgia's number as well would lead to double counting of cases.
