### ISSUE TITLE
Data Issue:  Crawford Co., KS

### ISSUE THREAD

**Issue by ke4roh** [nytimes/covid-19-data#286]
### Describe the issue:
- [x] Incorrect number of cases or deaths

### Fuller details
Per https://www.crawfordcountykansas.org/health-department.html , Crawford has had one new case on each except the first day, when they had 2. Here I list the cumulative totals along with the date of the change:

- March 23 - 2
- March 25 - 3
- March 28 - 4
- March 30 - 5
- April 2 - 6
- April 25 - 7
- April 30 - 8

**Comment by albertsun** [comment]
So, two of those cases the county is reporting they have been calling "presumptive". It seems unclear that those follow the same definition as we are using for probable cases elsewhere, and since the Kansas state dashboard is including probable cases itself, we're continuing to use the Kansas state dashboard number for Crawford county.

**Comment by ke4roh** [comment]
Please consider the discrepancy in April 27-30, where the case count goes from 6 to 7, back down to 5, and back to 6.

**Comment by albertsun** [comment]
We'll look more closely at that. We have reached out to the county and are waiting to hear back.
