### ISSUE TITLE
Data Issue:  King County, WA

### ISSUE THREAD

**Issue by loftusa** [nytimes/covid-19-data#289]
### Describe the issue:
Incorrect number of cases or deaths.

### Fuller details
The most recent data for King County shows 7848 as of 05/18: https://github.com/loftusa/covid-king/blob/master/dad_coronavirus.ipynb

But the King County data website shows a count of 7582 as of 05/18: https://www.kingcounty.gov/depts/health/covid-19/data/daily-summary.aspx

The other numbers are all slightly off as well.
What is the source of this discrepancy?

**Comment by amyswalk** [comment]
Hi Alex, thanks for your comment. We had briefly included antibody tests as positive cases but have now decided to leave those out (King County reports these in the text above its positive case count). We'll correct the historical data to reflect this change. Also, our data runs two cases and two deaths higher than the county's figures, due to nonresidents who were diagnosed and died in the state. We are also currently using the state's death figure, which is slightly higher than the county's.

**Comment by loftusa** [comment]
Great, thanks for the info!
