### ISSUE TITLE
Data Issue:  Hawaii

### ISSUE THREAD

**Issue by ke4roh** [nytimes/covid-19-data#294]
### Describe the issue:
- [X] Incorrect number of cases or deaths

### Fuller details
Hawaii's cumulative number of cases in us-states.csv goes down from May 21 to May 22.

**Comment by tiffehr** [comment]
I see a change the state published between 5/22/2020 1:15 p.m. EDT and 5/22/2020 6:00 p.m. EDT for probable cases, from 637 to 632.  (In fact, the change was within 15min of 6 p.m. that day.)  

This is straight from the state source and at their discretion to reclassify cases.  I expect this is one of those cases.  Hawaii describes their cases as:
> *Positive cases include presumptive and confirmed cases, and Hawaii residents and non-residents; data are preliminary and subject to change. Note that CDC provides case counts according to states of residence.

I expect testing labs moved two presumptive cases from to negative once lab tests provided more resolution.

**Comment by albertsun** [comment]
Earlier today Hawaii posted a note on their state dashboard saying "As a result of updated testing information, 5 cases were removed from the counts" — that note is gone now, but is the reason our count goes down by those 5.

**Comment by tiffehr** [comment]
@ke4roh Does this address your question?

**Comment by ke4roh** [comment]
I understand how the problem came to be. I think the data set should be changed to reflect the reclassification of those cases going back to the beginning of those cases so that the cumulative count doesn't decrease.

**Comment by tiffehr** [comment]
We have no data to support that.  We know about the counts but we know no details about the underlying cases with which to reclassify them.  I don't know how we would accurately reclassify them by date.

**Comment by salma71** [comment]
The fips for California are missing up after fetching the data - it reverses the state code probably because it is a float64. 
For example, Orange county in California's fips should be 06059; however, it parsed as 6059 as in the attached screenshot. 
 
![Screen Shot 2020-05-29 at 8 00 54 AM](https://user-images.githubusercontent.com/29179944/83257977-72fa1080-a183-11ea-9c99-08a91fc52c99.png)

I did a quick fix in the pd.read_csv() function by fetching the fips column as a string. 
`nyt_url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'`
`by_county = pd.read_csv(nyt_url, dtype={'fips': str})`

**Comment by ke4roh** [comment]
I have put in a question to the Hawaii folks to see if we can get some better data.
