### ISSUE TITLE
Data Issue:  Alachua County Florida data decreases on 5/16/2020

### ISSUE THREAD

**Issue by jstover79** [nytimes/covid-19-data#297]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Case count data for Alachua County Florida shows a decrease from 5/15 to 5/16. It is only a -1 change, so overall small. I imagine there are probably a few more, but I haven't checked all counties and dates yet.

I discovered this when comparing to county-level data from usafacts.org. Their data had many negative daily changes (-1067 cases total for just over 400 counties, which is overall a somewhat small discrepancy in the data). I saw the same issue with Georgia data posted here and that it was resolved. I imagine most negative values are also cases being allocated to out of state or out of county residents. It would be very nice to have a clean uniform solution for this. I have also alerted usafacts of this issue in their data.

Thanks for your attention to this matter and for maintaining this repository.

**Comment by albertsun** [comment]
Hi @jstover79 thanks for asking about this. Our data, like the USA Facts data is going to show many negative daily changes at the county level as well. That's because the ultimate sources for this data are frequently revising daily counts for individual counties down as they reassign cases to new locations or remove cases that were first added in error. In some cases we can make revisions to avoid a decrease in count but in the vast majority of them we are not able to.
