### ISSUE TITLE
Data Issue:  Change the fips dtype to int64 or str

### ISSUE THREAD

**Issue by salma71** [nytimes/covid-19-data#302]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- Other

### Fuller details
The fips for California are missing up after fetching the data - it reverses the state code probably because it is a `float64`. 
For example, Orange County in California's fips should be 06059; however, it parsed as 6059 as in the attached screenshot. 
 
![Screen Shot 2020-05-29 at 8 00 54 AM](https://user-images.githubusercontent.com/29179944/83257977-72fa1080-a183-11ea-9c99-08a91fc52c99.png)

I did a quick fix in the pd.read_csv() function by fetching the fips column as a string. 
`nyt_url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'`
`by_county = pd.read_csv(nyt_url, dtype={'fips': str})`

![Screen Shot 2020-05-29 at 8 22 02 AM](https://user-images.githubusercontent.com/29179944/83259146-873f0d00-a185-11ea-9677-a0a0e8971496.png)

**Comment by ke4roh** [comment]
This is not a problem in the data set, but a problem with the parsing of it.  The state code is 2 digits, and the county code is 3 digits, together making the 5 digits you see in the extract.  "Reversing" the state code appears to happen because you're seeing the low digit of the state code combined with the high digit of the county code.  If you must treat it as a number (and there are good reasons you might), int(code/1000) is the state, and code%1000 is the county.  

The FIPS code is 5 digits, provided in a string along with a bunch of commas, as seen in this excerpt:

```
2020-01-25,Orange,California,06059,1,0
2020-01-26,Orange,California,06059,1,0
2020-01-27,Orange,California,06059,1,0
2020-01-28,Orange,California,06059,1,0
2020-01-29,Orange,California,06059,1,0
```

**Comment by albertsun** [comment]
Hi @salma71, those data types `int64` or `str` or `float64` are all specific to your code there (Pandas, looks like?). As we've only posted a CSV file, everything is a plain string. Your solution looks like the right one to the problem of `read_csv` deciding to parse that column as a number, and hopefully other people will discover that as well. But there's nothing we can change in the data file to solve that!
