### ISSUE TITLE
Data Issue:  Since us-counties.csv represents cumulative cases, how can cumulative cases decrease sometimes as time increases?

### ISSUE THREAD

**Issue by ankit61** [nytimes/covid-19-data#317]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
I think in some cases (around 1%) the number of cases decrease with time in some counties. For example, for FIPS code 48441, there are 400 cases on 2020-05-21, but only 322 on 2020-05-22. In fact, the total number of deaths also decrease by 1 in that time period for that county. There are also many other examples I can show you when such behavior occurs. Some examples are below just to make this point:

1) Drop in cases by 9 from 2020-05-12 to 2020-05-13 in FIPS 48341
2) Drop in cases by 35 from 2020-05-22 to 2020-05-23 in FIPS 48225
3) Drop in cases by 14 from 2020-04-30 to 2020-05-01 in FIPS 08097

**Comment by jazz788** [comment]
I have seen it also, I assume it's because the local county health agencies etc.  are submitting a cumulative number each time, and if there was a mistake or overstatement in a prior submission , or a change in classification, then the new cumulative submission will account for that, sometimes resulting in a drop, it should also account for unusual increases as well, can work both ways. 

This is just my hypothesis, I look forward to hearing the official thoughts on this from the NYT team.

**Comment by albertsun** [comment]
Please see the Methodology section of the README under "Declining Counts" https://github.com/nytimes/covid-19-data#methodology-and-definitions

This is somewhat common across the dataset at the county level.
