### ISSUE TITLE
Data Issue:  Orange County, California new cases per day vary widely from OCHCA

### ISSUE THREAD

**Issue by plaza479** [nytimes/covid-19-data#324]
### Describe the issue: I'm the cutoff times vary for daily case counts between here and OC Health Care Agency, but over the last few days there seems to be a significant mismatch. 
Example: from 6/12 - 6/15 OCHCA reports 166,130,299,198 daily new cases; data here for those same dates are 82,136,141,178. Looking at the 4-day total to remove some cutoff effects shows OCHCA reporting 793 cases over those dates compared to 537 cases here. 

Link to OCHCA data: https://occovid19.ochealthinfo.com/coronavirus-in-oc
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources.

**Comment by albertsun** [comment]
HI @plaza479, in order to have the most up to date total case count, we use data both from Orange County Health and from the California DPH (data [here](https://data.chhs.ca.gov/dataset/california-covid-19-hospital-data-and-case-statistics/resource/6cd8d424-dfaa-4bdd-9410-a3d656e1176e)), taking whichever number seems more up to date from either source each day. On 6/12, our number came from DPH and on 6/15 our number came from Orange County.
