### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by furtip** [nytimes/covid-19-data#327]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

Data from Texas for yesterday looks wrong:

2020-06-15 | Texas | 48 | 91727 | 2018
2020-06-16 | Texas | 48 | 95973 | 2057

State of Texas is reporting only 2,622 new cases yesterday. Can you check this, because if it's actually 4,246 cases yesterday that is a significant and newsworthy difference.

https://www.keranews.org/post/covid-19-live-updates-gov-abbott-says-no-reason-today-be-alarmed-cases-set-record
https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83 (case trends tab)

**Comment by albertsun** [comment]
@furtip a large part of the increase is due to backlogged prison cases. We added this note to the README.

```
On June 16, Texas reported an additional 1,476 backlogged cases from prison inmates in Anderson and Brazoria counties.
```

There's a note on the Texas state dashboard that explains those extra cases as well.

Our numbers also include incremental cases reported by individual Texas counties that have more up-to-date case counts than the state dashboard.
