### ISSUE TITLE
Enhancement: "publish in this dataset a file with the population numbers that you are using"

### ISSUE THREAD

**Issue by curiouspeat** [nytimes/covid-19-data#333]
It seems obvious that the NY Times has and is using population numbers that correspond to the counties being tracked in this dataset.  Could you publish in this dataset a file with the population numbers that you are using?

It took me a while to put this together from US census records, but I don't know what to use for your Kansas City numbers and for the counties excluding Kansas city.

It would be really nice to have a data set with the same county and state columns that correspond to your county data columns.

I know its hard keeping this dataset up-to-date and accommodating new requests too but it would be much appreciated.

Thanks,
Peter Khoury (aka Peat)

**Comment by tiffehr** [comment]
A number of people using this public data set have offered up population-related add-ons. We collect most (if not all) of those requests or offerings on [our Project board](https://github.com/nytimes/covid-19-data/projects/1) for this repo, under Additive Data*. 
 I recommend checking for population-related efforts there.  

We use US Census data, specifically the American Community Survey 5-year data, through 2018. Kansas City and NYC are particular mapping efforts, because they mean taking county figures and negating the city _depending_ on how the relevant counties report data.

* not my best naming effort ever, but it is a broad group
