### ISSUE TITLE
Enhancement: Please include total cases in the data

### ISSUE THREAD

**Issue by dkyleward** [nytimes/covid-19-data#335]
I'm currently working with a dataset from https://covidtracking.com/ that includes total cases as well as new/positive cases. This has been really important to measure the rate of positive cases. The absolute number of cases can be distorted between states based on increased/decreased testing.

**Comment by albertsun** [comment]
@dkyleward I'm not quite sure what you are asking for here, the only figure we report in this data set is total cases.

**Comment by dkyleward** [comment]
Maybe I missed it, but from the covidtracking.com site:

![cases](https://user-images.githubusercontent.com/10221750/85571053-d8fe7a00-b601-11ea-8817-70e01df3c1c0.png)

Being able to normalize positive cases into a rate or percentage of total tests performed is the only way to accurately present trends over time or between states. Thanks for your time!

**Comment by albertsun** [comment]
So you're requesting we add total tests performed in addition to cases?

We early on made the decision not to track the total number of tests performed because that data was not available at the county-level. We've found COVID Tracking project data there to be of high quality.

Additionally, not all the cases in our data correspond to a positive lab test because of the way probable cases and deaths are defined and reported. You can read about that [here](https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md).

**Comment by dkyleward** [comment]
Thanks for the info. Feel free to close, but consider adding total cases to the higher geographies.

**Comment by tiffehr** [comment]
@dkyleward You just want the sums of what's in the .csvs?  There are as many CSV preferences as there are possible commas is CSVs -- some people want rows that add totals and others do not, because they have to then filter them out of their own sums.  The math to derive totals here is so direct, I think that should be the provenance of anyone using the data.  If the math were more complicated I could see reason we would do that ourselves.
