### ISSUE TITLE
Question:  Data on clusters

### ISSUE THREAD

**Issue by masaofukui** [nytimes/covid-19-data#339]
Thank you so much for providing amazing data!

I wondered whether there is any chance that the data on clusters ( https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html?fbclid=IwAR1TLZeQvxV55wryrwUOIhIPLAGFZ7bKmo5NS1zuVGvVWyfGRRuqdvPwaPg#clusters ) will be available here. I also wonder whether you have the information on the date when clusters happened. Thank you so much!

Regards,
Masao Fukui

**Comment by tiffehr** [comment]
We are unlikely to add cluster data here, since it does not roll up under geographies like counties and is already icluded in our county and state counts.  Our tracking methodology for clusters is not as automated as our broader covid-19 case data tracking, and represents a number of editorial judgments about the clusters.

Your point about the date is a good one, however.  I'll relay that to our Graphics desk for consideration in our public table of clusters.  It could benefit from the "when cases were..." horizontal bar charts we use for U.S. states & counties.
