### ISSUE TITLE
Data Issue:  Baseline Detroit data for deaths

### ISSUE THREAD

**Issue by dpropson** [nytimes/covid-19-data#345]
There are far too many deaths reported for the area described as "Detroit".  The weekly deaths in Detroit do not ordinarily run at the level given in the spreadsheet at all.  Is this listing deaths for the entire tri-county metro area?  If so, it needs to be mentioned.

**Comment by lwaananenjones** [comment]
Michigan reports Detroit and Wayne County separately on its [dashboard](https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html), but in our county-level data Detroit is included as part of Wayne County. Our dataset also includes prison cases and deaths, which the state puts in a separate category. But if you add the Detroit and Wayne County confirmed and probable deaths from the state dashboard, it should be very close to the Wayne County number in our data. For instance, on 6/27 the state reports 2,708 deaths (1,522 in Detroit and 1,186 in Wayne County) and our number is 2,710 after including prison deaths.

Some of our other graphics and trackers use other standardized regions, [such as metro areas](https://www.nytimes.com/interactive/2020/04/23/upshot/five-ways-to-monitor-coronavirus-outbreak-us.html), so that might be the difference you're seeing. The Metropolitan Statistical Area for Detroit includes six counties.
