### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by eemdub** [nytimes/covid-19-data#347]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The data for new cases in WI on June 10 seems erroneous. I've been checking the NYT site every day and just today there was a huge jump for June 10 (it wasn't previously that large) and many other days' numbers had been altered. Just wondering if there's a mistake in the data entry?

**Comment by lwaananenjones** [comment]
We made revisions on 6/26 to include Wisconsin's probable cases and deaths back to 6/10, so that's the jump you're seeing as well as the day-by-day revisions since then. The spike that's now showing on 6/10 includes cases and deaths likely going back months, but we don't have date information for those added cases unless the state provides it. We add notes to the readme file when there are unavoidable data reporting anomalies like this:

> Wisconsin started reporting probable cases and deaths on June 10, causing a large spike in the number of cases on that day. The total number of cases that day includes 2,407 newly reported probable cases.

A new feature this week on our [state tracker pages](https://www.nytimes.com/interactive/2020/us/wisconsin-coronavirus-cases.html) is that spikes from data anomalies are labeled directly on the charts.

![wi-probable](https://user-images.githubusercontent.com/47159046/85937725-2eb17b80-b8bb-11ea-8420-84943951fe59.png)

**Comment by eemdub** [comment]
Thanks for the update—I appreciate it.

Sent from my iPhone

On Jun 27, 2020, at 23:15, lwaananenjones <notifications@github.com> wrote:

﻿

We made revisions on 6/26 to include Wisconsin's probable cases and deaths back to 6/10, so that's the jump you're seeing as well as the day-by-day revisions since then. The spike that's now showing on 6/10 includes cases and deaths likely going back months, but we don't have date information for those added cases unless the state provides it. We add notes to the readme file when there are unavoidable data reporting anomalies like this:

Wisconsin started reporting probable cases and deaths on June 10, causing a large spike in the number of cases on that day. The total number of cases that day includes 2,407 newly reported probable cases.

A new feature this week on our state tracker pages<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.nytimes.com_interactive_2020_us_wisconsin-2Dcoronavirus-2Dcases.html&d=DwMCaQ&c=S1d2Gs1Y1NQV8Lx35_Qi5FnTH2uYWyh_OhOS94IqYCo&r=tQqXck0ZuthWi5oEaHG71sKsRmqtmLvXoX93d0KQGz-9c7l5gEVBSVArQ80WChzA&m=_G7Q924VxHINffe4jFXLn5VtcZXwujLDMyQZ4qCuRgE&s=tEQvBVbzJurvlJEJs1bazqQ_4uF6WT-oUMT9zcI1Y4Y&e=> is that spikes from data anomalies are labeled directly on the charts.

[wi-probable]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_47159046_85937725-2D2eb17b80-2Db8bb-2D11ea-2D8420-2D84943951fe59.png&d=DwMCaQ&c=S1d2Gs1Y1NQV8Lx35_Qi5FnTH2uYWyh_OhOS94IqYCo&r=tQqXck0ZuthWi5oEaHG71sKsRmqtmLvXoX93d0KQGz-9c7l5gEVBSVArQ80WChzA&m=_G7Q924VxHINffe4jFXLn5VtcZXwujLDMyQZ4qCuRgE&s=YgMu7zzldlTZNpVsRSyNYjzfwtfJ33rsB-MDaWhzbU0&e=>
