### ISSUE TITLE
Question: README explanation missing

### ISSUE THREAD

**Issue by dcthomas0518** [nytimes/covid-19-data#390]
Source: us-counties.csv

Where in the README is the explanation for why New York City suddenly reported 625 deaths on one day in bulk on June 30th? 

This appears NYC is gaming the reporting by systematically under-reporting daily deaths by previously excluding those 625 deaths.

NYC Deaths | Cumulative | Daily (derived)
26-Jun | 21,893 | 37
27-Jun | 21,913 | 20
28-Jun | 21,940 | 27
29-Jun | 21,941 | 1
30-Jun | 22,566 | 625
01-Jul | 22,574 | 8
02-Jul | 22,593 | 19
03-Jul | 22,610 | 17

Thanks

**Comment by ddenenberg71** [comment]
Looks like it was accidentally omitted when parts of the README were rearranged earlier today: https://github.com/nytimes/covid-19-data/commit/f0c3d4ced18ae085d2260425dce3bfd8739681d8

**Comment by albertsun** [comment]
Thanks @ddenenberg71 @dcthomas0518, due to an editing error this note was lost from the README but it's restored now. The NYC health department did announce these backlogged deaths on that day, they announced 692 in total and we counted 625 of them on that day after reconciling with the New York State health department numbers.

While releasing reports of deaths in bulk like this does seem like it would have the effect of under-reporting deaths on earlier days, we don't believe this to be "gaming the system" or anything malicious by the health department. It's simply a part of how deaths are recorded and reconciled across the country. Deaths take a while to register, record causes and match to case surveillance data, especially now when many are dying of a new disease. Some health departments may do this investigation to add additional deaths a few each day and add them to each day's count, some may do them in bulk like New York City has here, and most troublingly some may not have the resources to do it all. You can read more about the process of recording deaths in this article: https://www.nytimes.com/interactive/2020/06/19/us/us-coronavirus-covid-death-toll.html
