### ISSUE TITLE
Question:  Consider providing opt-in replacement for CDC repo 

### ISSUE THREAD

**Issue by estaub** [nytimes/covid-19-data#398]
You (nytimes) might consider volunteering to run a duplicate, PUBLIC repository for states to opt in to if they want their formerly public CDC data to remain so.

**Comment by amyswalk** [comment]
Thank you for the suggestion, Ed. Many states are reporting detailed hospitalization data on their public health department websites, though it's a bit of a patchwork. Illinois is one example ([see here](http://www.dph.illinois.gov/covid19/hospitalization-utilization)). [The University of Minnesota](https://carlsonschool.umn.edu/mili-misrc-covid19-tracking-project) and the [COVID Tracking Project](https://covidtracking.com/) have been collecting what the states provide since March. This new order from the administration shouldn't change what the states provide.

**Comment by estaub** [comment]
Thanks much.  One of the key values external sites like COVID Tracking Project and yours bring is _perspective_ - history.  Some states are no longer publishing any historical data.
