### ISSUE TITLE
Question:  Populations 

### ISSUE THREAD

**Issue by wesmor1231** [nytimes/covid-19-data#404]
I am trying to calculate the same per capita cases and deaths as on the NYT website. I thought I previously had this done, but it looks like the populations may have changed on the site map? anyone else having this issue or know where I can get the new numbers?

**Comment by GordonLElliott** [comment]
I am also looking for population data, for the same reason to calculate per capita statistics. All I have found is versions of the Census which takes estimates to July 2019:

[County Population Totals: 2010-2019](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html)
 
I wanted to express that others may also be needing a solution to this issue.

**Comment by tiffehr** [comment]
We have talked about our per capita calculations against population before:  https://github.com/nytimes/covid-19-data/issues/315#issuecomment-642084695

Perhaps those responses answer your question?

**Comment by GordonLElliott** [comment]
In part it does, the NY Times appears to have used "2014-2018 5-year ACS data". That data has an enormous amount of detail about demographics such as race, ethnicity, etc.

However it is 2 years out of date, while the [County Population Totals: 2010-2019](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html) is only one year out of date and is more "official" with respect to total population.
 
I was hoping that there were even more current estimates--for example projections to July 2020 would be more accurate for the per capita statistics than any of those.
 
If people would actually use that, I could do a curve fit on per-county population and project to either July-2020 or a function by month. Otherwise I think I will use the 2019 July data as best estimate for my purposes.

**Comment by albertsun** [comment]
Hi, yes, we've actually since switched over to using the 2019 Census population estimates in order to get more recent numbers.

I would again caution that we don't recommend trying to exactly replicate the numbers that we're publishing since we are constantly updating those pages as the situation evolves.

**Comment by GordonLElliott** [comment]
Great, thanks, at least that confirms what is thought to be the best method. I am trying to produce graphs over time from February for research and a talk, based on per-capita data (cases, deaths per 100,000 population). I think I can use that with confidence. Takes a bit of automated editing I think to get the county names in same format. If someone happens to have a version cleaned up to identical county designations, that would be helpful.
