### ISSUE TITLE
Enhancement: Historical county data only has the total case number

### ISSUE THREAD

**Issue by damaneice** [nytimes/covid-19-data#424]
### Describe the feature you would like to see
Thank you so much for providing this data set. Currently the historical data has the confirmed and probable case numbers combined. 
```date,county,state,fips,cases,deaths```
```2020-01-21,Snohomish,Washington,53061,1,0```
Would it be possible to include both in separate CSV fields?

Thanks again

**Comment by albertsun** [comment]
Hi @damaneice,

We'd like to provide that also, but one issue right now is, especially historically, there are many states / periods of time for which the state either only reported a combined number or for which it was unclear if the number they reported was a combined number or a confirmed-only number. It would take a fair amount of work, including getting more information from state health departments, in order to put together a quality historical data set with those fields separated. We haven't yet prioritized doing that work since we are not using the data in separate form ourselves.

If you or others have specific use cases for that separate data that you can share we would definitely consider it.

**Comment by damaneice** [comment]
Is the covid number for States the confirmed total?

https://github.com/nytimes/covid-19-data/blob/master/us-states.csv

**Comment by albertsun** [comment]
The numbers there are combined totals, confirmed and probable cases when probable cases are reported.

**Comment by damaneice** [comment]
Thanks! I'll close the issue
