### ISSUE TITLE
Question: Why does total cases decrease with time for some datapoints?

### ISSUE THREAD

**Issue by austinvhuang** [nytimes/covid-19-data#425]
### Do you think there is an error in the data?
Possibly.

### Do you have a question about the LICENSE or permission to use this data?
No

### Your question

While in most of the data, total cases monotonically increases there are instances where this is not the case. For example FIPS 25025:

```
2020-06-14,Suffolk,Massachusetts,25025,19335,950
...
2020-06-15,Suffolk,Massachusetts,25025,19334,951
...
2020-06-16,Suffolk,Massachusetts,25025,19367,952  
```

**Comment by tiffehr** [comment]
Local health authorities correct their data as they see fit, including backdating cases or deaths from the day they were first publicly tallied to a more correct date based on medical records.  We sometimes know when a health authority does this, because they announce it and even isolate the number of data points "moving backwards".  Other locations don't mention it except in the raw data like the timeseries you isolated for Suffolk, MA.  

There is more about this effect in the README, if you would like further information.
