### ISSUE TITLE
Question:  Historic data of confirmed cases by state

### ISSUE THREAD

**Issue by Shufan-uga** [nytimes/covid-19-data#433]
I'm investigating the relationship between the number of viral genomes available per state and the number of confirmed cases at the time of sampling. The study will lead to insights to the extend of missing data and sampling bias in current sequencing data. Subsampling schemes bases on these new knowledge results in more representitive phylogenetic and phylodynamic studies of SARS-COV-2 and more accurate identification of tramission risk factors. 

To achieve my goal, I would like to obtain historical data on the confirmed case count per state since the beginning of the outbreak in the US. Do you have the information available?

**Comment by lwaananenjones** [comment]
This dataset includes historical data based on the date cases were announced. It includes probable cases when available, so that may not serve your purposes for confirmed-only cases. Some states have never included probable counts, so those particular states would be available, and I can tell you which states fit that category if you only need a subset. We've attempted to collect confirmed and probable counts separately when available, but many states combine them.

**Comment by Shufan-uga** [comment]
Dear lwaananenjones,
Thank you for the speedy response. Please help me identify states that have only reported confirmed cases. That would be very helpful! Do you know other datasets that may have historical confirmed case information?

Sincerely,
Shufan
________________________________

**Comment by tiffehr** [comment]
If you need the difference between state confirmed and probable cases, the [CDC has CSVs with probable counts](https://www.cdc.gov/covid-data-tracker/index.html) for [states](https://www.cdc.gov/covid-data-tracker/Content/CoronaViewJson_01/US_MAP_DATA.json) and [counties](https://www.cdc.gov/coronavirus/2019-ncov/json/county-map-data.json).  The diff (or not) could provide that signal for you about which are not including probable cases.  

![image](https://user-images.githubusercontent.com/60173/90545393-96b36e00-e156-11ea-9de3-e8826ecd28a2.png)
