### ISSUE TITLE
Data Issue:  Dallas County Cases took a massive jump up the last two days. Does not seem credible.

### ISSUE THREAD

**Issue by Arcazares** [nytimes/covid-19-data#435]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by Arcazares** [comment]
The cases in Dallas county took a massive jump up in the last two days. This seem unrealistic.

**Comment by gmillikan** [comment]
Agreed, we received some feedback from our users who received our Dallas County email alert below asking about data glitches.  We usually just say “NY Times is almost always right on these things and it’s the county that’s got the glitch” but would welcome feedback on this one as it such a big county.  Thanks!

![0E08F857-4938-40E8-95EF-143ED44D6E6B](https://user-images.githubusercontent.com/63218226/90544191-a4a7c580-e13b-11ea-851f-826051788e95.png)

https://www.cvleaderboard.org/alert/

**Comment by tiffehr** [comment]
[Dallas County Health & Human Services](https://www.dallascounty.org/departments/dchhs/2019-novel-coronavirus.php) has started noting probable cases.  You can see the addition in a paragraph below their main table.
![image](https://user-images.githubusercontent.com/60173/90544579-50114400-e155-11ea-9d61-c008bc52e51a.png)

On August 16th, [they announced 5,361 new probable cases](https://www.dallascounty.org/covid-19/judge-press-releases.php).  As [they describe in the PDF](https://www.dallascounty.org/Assets/uploads/docs/covid-19/press-releases/august/081620-PressRelease-DallasCountyReports5361AdditionalPositiveCOVID-19Cases.pdf), the large number is due to state-level lab test delays.

We included their Probable cases in our counts over the last few days, but backdated some of it where we could.
