### ISSUE TITLE
Data Issue: Incorrect number of cases (CO Aug 23)

### ISSUE THREAD

**Issue by Pete3465** [nytimes/covid-19-data#444]
On August 23, NYTimes is reporting 502 new cases for Colorado, which is almost double the number reported by the state of Colorado which reported 260. 

Normally the numbers reported are close to each other but not in August 23.  This number is higher than the total reported for Aug 23 & 24th combined

**Comment by albertsun** [comment]
Hi @Pete3465, our number is higher than Colorado's state number because we are using figures from certain counties that report more cases or in advance of the state. In particular, we noticed then that in Adams, Arapahoe, and Douglas counties the Tri-County Health District had many more cases than the state department of health.
