### ISSUE TITLE
Data Issue:  Was Massachusetts' count of cases restated? (around 9/3/20)

### ISSUE THREAD

**Issue by BAR-B-Q** [nytimes/covid-19-data#447]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [X] Other

### Fuller details

Was Massachusetts' count of cases restated?  Based on yesterday's count (for 9/2/20) and today's (for 9/3/20) it shows a -7342 count drop.  And looking through the State table it looks as though previous dates were updated to differing numbers (ex:  I showed yesterday's (9/2/20) count to be 128888 and now it shows 121131.  Are these changes highlighted somewhere so I can understand them (sorry to bother you if so, I just can't find it)?  Thank you in advance for your help.

**Comment by peterdaytx** [comment]
The county numbers have also changed radically for 9/3 vs 9/2, and although the "known" county numbers for 9/2 are consistent with 9/1, a large number of cases were dropped from "Unknown" county on 9/2...

**Comment by albertsun** [comment]
We are now noting these kinds of anomalies directly on our state pages. The Massachusetts one is here: https://www.nytimes.com/interactive/2020/us/massachusetts-coronavirus-cases.html#anomaly-notes

This drop in cases is due to the state changing it's methodology for counting probable cases as described here in their release: https://www.mass.gov/doc/covid-19-dashboard-september-2-2020/download

Previous cases that were identified by serological testing plus symptoms or exposure are now no longer being counted as cases by Massachusetts.

**Comment by stephen304** [comment]
According to the MA link, they updated the previous data to reflect the change in definition. Should the data here be retroactively updated to provide consistency?

**Comment by albertsun** [comment]
We're going to assess to see if that makes sense. The dataset here is generally cases as they were reported at the time so we try to be more conservative about making historical revisions like that, especially if they are downward revisions.
