### ISSUE TITLE
Data Issue: Dallas County cases haven't increased in a week 

### ISSUE THREAD

**Issue by ghop02** [nytimes/covid-19-data#472]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Dallas County cases have not increased since 10-05, but the daily reports indicate there are more cases.

Note that deaths have increased.

**Comment by gadavi1** [comment]
I agree that this is an issue. Dallas county has been announcing new cases since 10-05 (so no apparent back log), but these counts don't seem to be included in the data.

See links below, which show new case counts for Dallas county on 10-10 and 10-11.

https://www.dallasnews.com/news/public-health/2020/10/11/dallas-county-reports-418-cases-and-four-deaths-tarrant-county-reports-most-single-day-coronavirus-cases-in-almost-two-months/
https://www.dallasnews.com/news/public-health/2020/10/10/dallas-county-adds-460-confirmed-coronavirus-cases-1-death-officials-warn-of-rising-hospitalizations/

**Comment by albertsun** [comment]
Thanks for pointing this out. Dallas recently changed how they surface information about probable cases and our total went out of date based on that. We're doing a review of the historical data here and will revise it and update shortly.

**Comment by gadavi1** [comment]
Excellent! It looks like the issue is resolved.

Thanks so much for all the hard work updating and maintaining this database.
