### ISSUE TITLE
Add Recovered Stat- and Thank you NYT

### ISSUE THREAD

**Issue by tooslowsarah** [nytimes/covid-19-data#48]
Consider adding column showing number of recovered individuals. Thank you for sharing this info with the world.

**Comment by paulmills-cd** [comment]
Concur - 'recovered count' field would add value.  Also - can you confirm that the 'cases' field refers to cumulative active cases, meaning if someone dies or recovers, they are no longer in this total?

**Comment by albertsun** [comment]
I'm catching up on these issues now.

Data on the number of recovered cases is not available consistently at the county level. Active cases in particular are difficult because health systems do not always follow up with people who have tested positive to see if they have recovered.

Some places are reporting that data, but for this release we focused on what we could do consistently nationwide.
