### ISSUE TITLE
Data Issue:  Los Angeles County, November 5

### ISSUE THREAD

**Issue by amhirsch** [nytimes/covid-19-data#496]
### Describe the issue:
- [ x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

The total cases count in Los Angeles County disagrees with the numbers reported by County of Los Angeles Department of Public Health. These sources have the same data points until November 5th and it continues through the current date. I am unaware of any changes to Los Angeles' reporting standards starting on November 5th.

Date | LA Public Health | NYT
---- | ---- | ----
2020-11-03 | 311745 | 311745
2020-11-04 | 313526  | 313526
**2020-11-05** | 315564 | 315634
**2020-11-06** | 317656 | 317727
... | ... | ...

**Comment by albertsun** [comment]
Hi @amhirsch,

That's when Pasadena started reporting probable cases, i.e. those identified with antigen tests. https://www.cityofpasadena.net/covid-19/#dashboard

Since LA county in their total doesn't report these cases but our overall methodology, and that from the CDC and CSTE does, we've added the ones reported by Pasadena to our overall total.
