### ISSUE TITLE
Enhancement: include prisons/jail/nursing classification associated with county infection rates

### ISSUE THREAD

**Issue by jhpoelen** [nytimes/covid-19-data#497]
### Describe the feature you would like to see
Using your visualization of the county level covid19 infection rates, I was able to quickly see the countries with the most infections (e.g., see attached image). 

However, I was unable to see the kind of people that were infected (prison/jail/nursing/students/factory)within the county .

 In looking at Texas counties of Jones https://en.wikipedia.org/wiki/Jones_County%2C_Texas  and Gray  https://en.wikipedia.org/wiki/Gray_County%2C_Texas , I noticed that these small counties have correctional facilities (see https://www.countyoffice.org/tx-gray-county-jails-prisons/ https://www.countyoffice.org/tx-jones-county-jails-prisons/ ). 

https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html?action=click&module=Top%20Stories&pgtype=Homepage

> A clear and concise description of what you want to see within our data sets

In future visualizations, I would like to see a visual clue as to whether counties have significant population of incarcerated / nursing folks that live relatively isolated from the general population.

![Screenshot from 2020-11-15 07-48-09](https://user-images.githubusercontent.com/1084872/99190013-11b9ff80-2719-11eb-897b-e1ec946f615d.png)

**Comment by tiffehr** [comment]
We have broken out those numbers in a separate table, because the list is intensive, and in some cases it crosses county and state lines:  https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html#clusters  It is not easy to roll up those figures to specific counties, nor do we have a lot of room given the number of ways we communicate caseloads.  I recommend you cross-reference the lists.

![image](https://user-images.githubusercontent.com/60173/99451662-c140ce80-28df-11eb-993a-0a21956a230f.png)
