### ISSUE TITLE
Data Issue:  Cases in Durham County, NC

### ISSUE THREAD

**Issue by link2matt** [nytimes/covid-19-data#515]
I want to draw attention to some unusual reports of zero cases in Durham County, NC on three days in December. On 12/6, 12/10, and 12/11 there were no new cases reported in Durham County in this dataset. From 12/1 through 12/13 the total number of new cases in Durham County is 1,291 in the dataset. As a comparison, I manually copied Durham County new cases from the NCDHHS dashboard; their total case count for those dates is 1,427.

Here's the link to the NCDHHS dashboard where you can filter by county:
https://covid19.ncdhhs.gov/dashboard/cases

Here are the numbers that I manually copied from the dashboard:
12/1/20    54
12/2/20    100
12/3/20    81
12/4/20    111
12/5/20    103
12/6/20    78
12/7/20    81
12/8/20    83
12/9/20    87
12/10/20    150
12/11/20    148
12/12/16    182
12/13 16    169

1,427 New Cases

Thank you for providing this valuable dataset. I would appreciate any insights that you can provide on this apparent discrepancy between this dataset and the NCDHHS.

**Comment by tiffehr** [comment]
To make sure I follow, here you have done the math to show the increases in cases/deaths between consecutive days and compared it to the same figure provided by North Carolina's DHHS?  

The data we provide for Durham County, NC is cumulative and shows a steady progression, from 11,394 cases & 117 deaths (12/01) to 12,598 & 127 (12/13).  We use multiple data sources, including NCDHHS and Durham's own DPH.  We source different parts of our figures [from multiple sources, based on speed and consistency](https://github.com/nytimes/covid-19-data#methodology-and-definitions).  

I see a few days without an increase in cases -- the dates you noted.  That is not irregular based on reporting gaps, but _depending_ on the sources and tabulations we derive for that day, those probably should not be no-data days.  If that's a correct connection of what you're reporting back to our data (no additional math), we'll look into it.

date | county | state | fips | cases | deaths
-- | -- | -- | -- | -- | --
2020-12-01 | Durham | North Carolina | 37063 | 11559 | 122
2020-12-02 | Durham | North Carolina | 37063 | 11649 | 122
2020-12-03 | Durham | North Carolina | 37063 | 11766 | 124
2020-12-04 | Durham | North Carolina | 37063 | 11888 | 126
2020-12-05 | Durham | North Carolina | 37063 | 11958 | 126
2020-12-06 | Durham | North Carolina | 37063 | 11958 | 126
2020-12-07 | Durham | North Carolina | 37063 | 12143 | 126
2020-12-08 | Durham | North Carolina | 37063 | 12291 | 128
2020-12-09 | Durham | North Carolina | 37063 | 12431 | 128
2020-12-10 | Durham | North Carolina | 37063 | 12431 | 128
2020-12-11 | Durham | North Carolina | 37063 | 12431 | 128
2020-12-12 | Durham | North Carolina | 37063 | 12598 | 128
2020-12-13 | Durham | North Carolina | 37063 | 12767 | 128

**Comment by link2matt** [comment]
Thank you for looking into the Durham data. I think you have understood me correctly. For the NYT data,  I generated a new cases number for a day by subtracting a the previous day's cases number. The NCDHHS dashboard displays new cases by day over time and not cumulative numbers.

Here are the new cases numbers that I generated from the NYT data:
|county |date       | newCases| cases|
|:------|:----------|--------:|-----:|
|Durham |2020-12-01 |       83| 11559|
|Durham |2020-12-02 |       90| 11649|
|Durham |2020-12-03 |      117| 11766|
|Durham |2020-12-04 |      122| 11888|
|Durham |2020-12-05 |       70| 11958|
|Durham |2020-12-06 |        0| 11958|
|Durham |2020-12-07 |      185| 12143|
|Durham |2020-12-08 |      148| 12291|
|Durham |2020-12-09 |      140| 12431|
|Durham |2020-12-10 |        0| 12431|
|Durham |2020-12-11 |        0| 12431|
|Durham |2020-12-12 |      167| 12598|
|Durham |2020-12-13 |      169| 12767|

**Comment by tiffehr** [comment]
Thank you. I'd pull in one more column into your table:  the _cumulative_ cases reported by the NCDHHS for each day.  It's impossible to reconstruct that history in [their Tableau dashboard](), but they had days when the state or county's figures went backwards. 

county | date | newCases | NYT cases | Durham or NCDHHS cumulative | Negative change
-- | -- | -- | -- | -- | --
Durham | 2020-12-01 | 83 | 11559 | 11,559 |  
Durham | 2020-12-02 | 90 | 11649 | 11,649 |  
Durham | 2020-12-03 | 117 | 11766 | 11,766 |  
Durham | 2020-12-04 | 122 | 11888 | 11,888 |  
Durham | 2020-12-05 | 70 | 11958 | 11,958 |  
Durham | 2020-12-06 | 0 | 11958 | 11,791 | <=
Durham | 2020-12-07 | 185 | 12143 | 12,143 |  
Durham | 2020-12-08 | 148 | 12291 | 12,291 |  
Durham | 2020-12-09 | 140 | 12431 | 12,431 |  
Durham | 2020-12-10 | 0 | 12431 | 12,186 | <=
Durham | 2020-12-11 | 0 | 12431 | 12,327 | <=
Durham | 2020-12-12 | 167 | 12598 | 12,598 |  
Durham | 2020-12-13 | 169 | 12767 | 12,767 |  

Since our figures are _only_ cumulative, we pin the previous day's value when they're in the middle of revising counts or changing methodology.  If we hear instructions about how to historically reallocate those changes, we do it. If we don't, we can't guess.
