### ISSUE TITLE
Data Issue:  Incorrect number of deaths in Colorado

### ISSUE THREAD

**Issue by liamwarfield** [nytimes/covid-19-data#518]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Colorado releases 2 numbers for deaths, deaths among cases and deaths due to Covid-19. The data that the times is using is the deaths among cases. This number is much higher than the amount of deaths in the state (3427 vs 4368) due to covid.

**Comment by lwaananenjones** [comment]
This is correct, our data uses Colorado's "Deaths Among Cases" count since this is how the state reports county-level numbers. When Colorado first started reporting two statewide death counts in May, nearly all other states used a comparable "deaths among cases" standard for reporting deaths. Since then, many states have established a [reconciliation process between case records and death certificates](https://www.nytimes.com/interactive/2020/06/19/us/us-coronavirus-covid-death-toll.html), and some now rely entirely on death certificates. Death certificates are ultimately more accurate, but also create more lag since they are slower to process.

**Comment by liamwarfield** [comment]
Both counts are almost the same until you get within 1 month of today. After that, the counts diverge because death certificates are still rolling in. I guess I learned something today! I'm going to close the issue.
