### ISSUE TITLE
MN Data Obsolete

### ISSUE THREAD

**Issue by ABruceJacobs** [nytimes/covid-19-data#521]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

MN Has published updated vaccination data:
https://www.health.state.mn.us/diseases/coronavirus/vaccine/stats/admin.html

**Comment by tiffehr** [comment]
A point of clarification:  we are not including vaccination data in our dataset.  It's too new and volatile.  So is this marking that our current data (sans vaccination figures) is out of date for MN?

**Comment by ABruceJacobs** [comment]
Yesterday, this web page

https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html?action=click&module=Top%20Stories&pgtype=Homepage

 

....was out of date, showing 3,000 for MN, and referenced the GitHub site as the data source.

 

This morning, It has a much higher number: 48,189. and instead references the CDC page:

https://covid.cdc.gov/covid-data-tracker/#vaccinations

 

The CDC data is much higher than MN DOH, (38,284), 

https://www.health.state.mn.us/diseases/coronavirus/vaccine/stats/admin.html 

 

But the MN DOH site previously had mentioned that it does not include the BIA and VA Federally administered shots.

 

Thanks for being on it.

 

Good data is gold.

 

Bruce Jacobs

St. Paul

**Comment by tiffehr** [comment]
This data set here does not include vaccination information at this time.  It is among the sources used [in our graphic](https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html), but the primary source for now for all vaccine data is the CDC.  If their numbers are low due to the state not quite following the same methodology as others, there's little we can do about it.  We are working on the accuracy of our vaccine data and using multiple sources.  But this specific data set is separate from that effort.

Much obliged for the report.  We are also keeping tabs on large jumps in the CDC data and possible causes.  We are still in the first days of vaccine data reporting.
