### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by jestabil** [nytimes/covid-19-data#524]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
new daily cases for Texas increments by +1 each day since Dec 12, 2020 -this is statistically improbable. Also, strange 58K+ new daily cases reported for Texas on Dec 11, 2020

**Comment by lwaananenjones** [comment]
The large increase on Dec. 11 is when the Texas Department of State Health Services [began including probable cases](https://www.dshs.texas.gov/news/releases/2020/20201211.aspx). The state added more than 140,000 probable cases on that date, but the increase in our data is not that large because many counties had already been reporting probable cases. Anomalies like this are noted on our [state tracker pages](https://www.nytimes.com/interactive/2020/us/texas-coronavirus-cases.html).

Can you explain more about what you're seeing with the +1 increments? I'm seeing a wide range of new daily counts since Dec. 12.

**Comment by jestabil** [comment]
> The large increase on Dec. 11 is when the Texas Department of State Health Services [began including probable cases](https://www.dshs.texas.gov/news/releases/2020/20201211.aspx). The state added more than 140,000 probable cases on that date, but the increase in our data is not that large because many counties had already been reporting probable cases. Anomalies like this are noted on our [state tracker pages](https://www.nytimes.com/interactive/2020/us/texas-coronavirus-cases.html).
> 
> Can you explain more about what you're seeing with the +1 increments? I'm seeing a wide range of new daily counts since Dec. 12.

Thank you for this explanation. There is no issue in the data: it was a calculation mistake I made*. I really appreciate your prompt response!  

*I included a link to Texas site to compensate for 12/11 data ...and forgot to update the link over the holidays, so I had a mistake in my daily-new-cases calculation which I was able to see when I corrected the 12/11 data based on your comment.

**Comment by tiffehr** [comment]
Thank you for the update!  We'll close the issue, but we're glad we could help find out what the discrepancy was.  All the best with your work!

**Comment by jestabil** [comment]
Thank you… I pull state level data -and do not cull it- for friends every week. Here’s a sample from Sunday. Best, José
