### ISSUE TITLE
Data Issue:  New York State Total Cases and Total Deaths isn’t matching up with John Hopkins University Coronavirus Resources Center or Worldometer website. Here’s the link to Worldometer website the correct information. https://www.worldometers.info/coronavirus/usa/new-york/

### ISSUE THREAD

**Issue by Monesha67** [nytimes/covid-19-data#538]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
A clear and concise description of the problem, with examples if possible. If you are reporting incorrect data for a specific locality, please include a link to your source.  We will compare with our own list of sources. Please check the README and recent commit messages for updates to see if your issue is addressed.

**Comment by PatrickDRusk** [comment]
With respect, that was the first reason I switched my data source to this repo. Better handling of New York's data.

**Comment by tiffehr** [comment]
We've written about how our data set differs from other sources, in our README.  Much of it has to do with some tough choices about source speed, veracity and clarity, in how they describe things. JHU's figures have never directly aligned with ours, due to the variety of decisions each team is making day by day.
