### ISSUE TITLE
Ohio's covid19 Spiked to 721?

### ISSUE THREAD

**Issue by davidjayjackson** [nytimes/covid-19-data#542]
### Describe the issue:
- [ *] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Did Ohio daily covid-19 deaths for Feb. 12, 2021, really spike to 721?  While daily deaths for Feb. 11, 2021, was only 63.

**Comment by PatrickDRusk** [comment]
This sort of thing happens often when states audit their results. It is noted on both https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html and https://www.nytimes.com/interactive/2020/us/ohio-coronavirus-cases.html. You need to correct for these things from time to time.

**Comment by tiffehr** [comment]
They are clearing a backlog of records.  "These deaths will be added to the state’s death count during the coming week."  [Press release](https://odh.ohio.gov/wps/portal/gov/odh/media-center/odh-news-releases/odh-news-release-02-10-20)  We have marked this spike as an anomaly [in our pages for Ohio](https://www.nytimes.com/interactive/2020/us/ohio-coronavirus-cases.html).

![image](https://user-images.githubusercontent.com/60173/107799008-2018b700-6d1a-11eb-9fdb-e39f1d37c3cd.png)

**Comment by PatrickDRusk** [comment]
You can get a date-of-death dataset for Ohio from https://coronavirus.ohio.gov/static/dashboards/COVIDSummaryData.csv. Even with that date, I have to ignore the last 50 days and project the rest from hospitalizations. But I hope that this audit will bring that date-of-death data much more up-to-date, too.

**Comment by davidjayjackson** [comment]
Well! This is interesting....
https://wpta21.com/2021/02/12/governor-expected-to-discuss-underreported-covid-19-deaths/

**Comment by PatrickDRusk** [comment]
I have been analyzing the death data from early on in the pandemic, first for the northeast, and then covering all 50 states and DC from about mid-summer using COVID Tracking Project and NY Times data. They have been great sources. But it has been abundantly clear that the daily new deaths reported stat needs tons of cleanup. I had about 50 adjustments that I would make, plus categorizing each state based on the impact of weekends and holidays on their reporting.

Starting about two months ago, I aggressively started incorporating date-of-death datasets from states that provide them, and various strategies for dealing with the incompleteness in recent weeks in such sets. I'm up to 23 states handled this way. This made it very clear, for instance, that there were not super-spreading spikes around Thanksgiving and Christmas, but just the continuation of the same slope from earlier in the fall, cresting around January 7 and falling since.

When researching the best way to project the final few incomplete weeks of date-of-death data, I made the startling -- but so entirely rational that it should have been expected -- discovery that deaths are highly correlated (98%+ in most states) with current hospitalization rates, with varying lags generally around 3-4 days. After my months of hard work trying to rationalize the death data, I finally concluded:

> If you want to track the *trends* of the epidemic, just look at the current hospitalizations rate. Nothing else matters.

The current hospitalizations rate appears to be reported accurately and very up-to-date everywhere. It is not impacted by weekends, holidays, bad weather events, audits, or reporting lags like confirmed cases, daily new deaths, or even date-of-death reporting are. It's error bars are much smaller than anything else.

If states reliably reported "new" hospitalizations, we would have the best, least-lagged indicator of the trends in an area. Alas, that is not reported reliably by many important states. Too bad. That leaves the current hospitalizations as the king of statistics in the US epidemic.

**Comment by davidjayjackson** [comment]
Patrick,
Thanks for your reply. Very interesting.
Did you see where COVID Tracking Project is going to be ending in Mar. 2021?
What method's do you use to evaluate the quality of the data? Do you
work with R? Is your code available?

What about daily cases? Are you seeing any signs of fiddling with those numbers?
Thanks again,
David Jackson

BTW, if you want to see some "interesting "  numbers take a look at Sweden...

**Comment by PatrickDRusk** [comment]
David,

Feel free to contact me at PatrickDRusk@gmail.com to continue this discussion so we don't pepper everyone that is following this issue. 

My code is available at https://github.com/PatrickDRusk/covid, with the caveat that it is the outgrowth of a obsessive side project during the pandemic, and the code is of "only a mother could love" quality. There are a number of data sources that are not yet documented in it because of the furious pace at which I added date-of-death sources in the last month.

Ping me, and I can answer the other questions.

Patrick

**Comment by tiffehr** [comment]
@PatrickDRusk Thanks for your summary of your work and analysis.  This tracks with some of our internal discussions, as well as ones we have had with the Covid Tracking Project and others.  Federal hospitalizations data -- while late to the game -- is pretty good on this account.  Our work with that data is also reflected in your findings, which is good to hear.

**Comment by davidjayjackson** [comment]
What was it  President Ronald Reagan said,  "trust and verify"

**Comment by PatrickDRusk** [comment]
@tiffehr Thank you for all the work that you guys have done. It has been a joy working with your data. It is bittersweet that the hundreds of hours I've put into refining my analysis of confirmed case and death data has made me realize that it is largely ignorable for studying the trends, given the far more accurate hospitalization data. But the journey has been a fun one.
