### ISSUE TITLE
Data Issue: Ohio: Have you folded in the corrected  deaths counts? 

### ISSUE THREAD

**Issue by davidjayjackson** [nytimes/covid-19-data#543]
### Describe the issue:
- [* ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
In the last 24 hours, Ohio released a "revised" count for Covid-19 deaths going back to Apr 1, 2020?

Thanks for looking into this,

David Jackson

**Comment by lwaananenjones** [comment]
Ohio added [more than 4,000 deaths in the past few days](https://www.nytimes.com/2021/02/12/world/Ohio-Covid-deaths.html) that officials indicated are older, and these are included in our data. There are notes on our [tracker page](https://www.nytimes.com/interactive/2020/us/ohio-coronavirus-cases.html) to indicate which daily counts are affected. Ohio publishes a CSV file each day with the date each death occurred, and from that file we can tell most of these deaths occurred in December, with some in October and November. 

It's our methodology to count cases and deaths on the day they are announced by officials, rather than date of death, since this is the only way to standardize across jurisdictions. But in this case the belatedly announced deaths have such a large impact on the state's curve that we're evaluating options for a possible revision. Ohio has indicated there may be additional updates coming up:

> The Bureau of Infectious Diseases and the Bureau of Vital Statistics continue to reconcile death data. This process is ongoing as the teams complete a deep review of the data. This review will result in some fluctuations in death numbers moving forward.

**Comment by davidjayjackson** [comment]
Thanks for following up.
