### ISSUE TITLE
Question:  How much confidence is there in the data being reported from Utah?

### ISSUE THREAD

**Issue by BAR-B-Q** [nytimes/covid-19-data#553]
Observation:  Utah falls in the top 10 states in the count of Cases when comparing to state population and in the bottom 10 states in Deaths.  Should the reported data be questioned or is it just the population make up (maybe people are younger, healthier, and/or more resilient to dying from COVID) or better protecting the most vulnerable or better at handling COVID cases that prevent death?

**Comment by lwaananenjones** [comment]
These are good questions about demographic impacts and responses that our dataset here cannot fully answer. Utah's population is younger than the [national median](https://www.census.gov/library/visualizations/interactive/2014-2018-median-age-by-county.html), and this could be analyzed by county.

Utah was one of the first states to report cases based on [antigen testing](https://www.nytimes.com/interactive/2020/11/01/us/antigen-testing.html), so that may have a small impact compared to other states that don't report antigen cases or waited several months to do so. Utah's state and local health officials have consistently answered our questions about how cases and deaths are counted, and the methodology aligns with national standards.

**Comment by tiffehr** [comment]
I'll add as a resident of Utah that local media has been very thorough in tracking cases/deaths and asking questions of Utah's state and local health department officials. I'd recommend reading some of their reporting about the way Utah has handled the pandemic.
