### ISSUE TITLE
Data Issue:  New York State incorrect numbers and incorrect deaths. 

### ISSUE THREAD

**Issue by Monesha67** [nytimes/covid-19-data#562]
New York State incorrect total cases, total deaths, and new cases from New York Times system. 
![FF282E22-7B06-4738-9EC1-1ABA08CEDCF9](https://user-images.githubusercontent.com/75553737/112708327-8f7fdb80-8e6e-11eb-82cd-765356ccb159.jpeg)
![53AA15A9-9CC8-426D-9F6D-99AE65483150](https://user-images.githubusercontent.com/75553737/112708328-90b10880-8e6e-11eb-9327-276683683d16.jpeg)
![DD636795-10D4-4992-859B-EF57AB2F915C](https://user-images.githubusercontent.com/75553737/112708329-90b10880-8e6e-11eb-90af-167847e60297.jpeg)
![9B309163-F6CD-4CB6-9DE6-EF2261F69851](https://user-images.githubusercontent.com/75553737/112708330-91499f00-8e6e-11eb-960f-6e1134b6e3d3.jpeg)

- [ ] Incorrect number of cases or deaths

Please update New York State Total Cases. Please update your system the correct number is 1, 874,258 from Worldometer website. The total death is incorrect in the system. 49,363 incorrect.
The correct numbers on the total death is 50,157
Worldometer website.

https://www.worldometers.info/coronavirus/usa/new-york/

**Comment by lwaananenjones** [comment]
The counts in our dataset often do not perfectly align with other datasets for various reasons of methodology and timing. We are not connected to Worldometer and it is not a source for this dataset; all our sources are government agencies and officials.

In New York, we use a combination of state data and county data, most notably for New York City. In our data, we are cautious about avoiding double-counting cases that may be reported in multiple jurisdictions. There are some counties in New York that report higher counts than the state because of non-standard methodology, in which case we use the state's counts for consistency.
