### ISSUE TITLE
Data Issue:  Dallas County, Alabama has frequently had total cases shrink

### ISSUE THREAD

**Issue by cfhp1** [nytimes/covid-19-data#576]
Incorrect number of cases or deaths

FIPS 01047, Dallas County, Alabama, has shown total cases decrease and grow again many times. In recent days, the total was 3,530 on 4/22/21, and falling to 3,529, 3,518 and 3,517 on subsequent days. There's another example starting on 4/13, another on 4/6, another on 3/30, and more earlier. The first example is 4/11/20. It's a small county, and neither the absolute numbers nor the percentage total are large, but I'm wondering if we know why this county is so often being restated downward. Overall, the total is 63 cases or 1.8% lower than it would be without the many adjustments downward.

**Comment by lwaananenjones** [comment]
This pattern of small decreases is fairly common, so we don't have a specific explanation for Dallas County. Alabama offers documentation for any large backlogs and adjustments, but officials have declined to answer our requests for additional context about data adjustments. 

In some instances we can revise a county's data if cases were erroneously added and later removed, but in most cases we can't do that accurately because we don't know whether cases were removed entirely (such as cases found to be duplicates) or reallocated to a different county or state. Frequent, small adjustments are most often related to residency; for instance, cases may be assigned to the location of the lab/provider if information is limited, then moved to the person's location of residence once full information comes through. States vary on whether they prioritize reporting cases quickly with the possibility of revisions later vs. waiting for accurate information even though it creates a lag.

**Comment by cfhp1** [comment]
It's so rural (37k in the county) that it's not obvious to me why test results would be wrongly assigned there to start. It has only recently been significant enough to cause a week over week calc to go negative so I wanted to ask the question. Thanks for having followed up. I truly appreciate the service you provide.

Carolyn
