### ISSUE TITLE
Charleston SC May 15 cases number looks like a big error

### ISSUE THREAD

**Issue by kathykchs** [nytimes/covid-19-data#584]
### Describe the issue:
- [x] Incorrect number of cases or deaths

### Fuller details
I can't find anything in the SCDHEC data to justify the 445 new cases reported on your Charleston SC chart for May 15. I believe it was a typo. https://www.nytimes.com/interactive/2020/04/23/upshot/five-ways-to-monitor-coronavirus-outbreak-us.html?action=click&module=Spotlight&pgtype=Homepage#hotspots

**Comment by lwaananenjones** [comment]
Thank you for asking about this. Our counts for South Carolina come from the state health department and match the state's published cumulative counts. We observed similarly large increases for several other counties in South Carolina on May 15, so we're hoping to get information from the state about whether this represents a backlog or data adjustment.

**Comment by kathykchs** [comment]
I don't think that is true...Here is the DHEC data for Charleston County. There is no uptick that day. https://scdhec.gov/covid19/south-carolina-county-level-data-covid-19

**Comment by albertsun** [comment]
The chart that the DHEC displays is based on backdating cases even when they are reported after the fact. The chart on our pages is based on assigning all cases to the day they are first reported, even if it was an older case. This means that the case totals are the simple difference of the cumulative total on each day minus the previous day. We use this method in order to keep case reporting consistent on a nationwide basis.
