### ISSUE TITLE
Enhancement: Daily vaccination data by county

### ISSUE THREAD

**Issue by lucymli** [nytimes/covid-19-data#585]
Feature request: The vaccination data behind this page: https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html. Ideally with the following columns: 

> date, county, state, num of 1st doses by age group, num of 2nd doses by age group

The [CDC website](https://covid.cdc.gov/covid-data-tracker/#county-view) only allows downloading one state at a time, only provides the current (not past) cumulative numbers, and does not include Texas.

**Comment by tiffehr** [comment]
Our source is predominantly the [CDC's Community Profile vaccine figures](https://beta.healthdata.gov/National/COVID-19-Community-Profile-Report/gqxm-d9w9).  They also have a CSV of [all current county vaccine data](https://beta.healthdata.gov/dataset/COVID-19-Community-Profile-Report-County-Level/di4u-7yu6). Additionally, we have pulled in data from [Texas DHS sources](https://tabexternal.dshs.texas.gov/t/THD/views/COVID-19VaccineinTexasDashboard/Summary?:embed=y) to patch in their figures per county.

Because we use the CDC's data for the majority of the country, we will not be making any vaccine-oriented data available here as a source.  We recommend working with the CDC's data, and per-state for those not included in the CDC's feed.
