### ISSUE TITLE
Data Issue:  Rhode Island Cases

### ISSUE THREAD

**Issue by Paracutin1** [nytimes/covid-19-data#590]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
There seems to be an issue with Rhode Island cases. From May 11-  May 23 the cases don’t change in the counties file however the state file they do

**Comment by lwaananenjones** [comment]
Rhode Island was unable to publish its regular weekly update last week because of database maintenance. Typically the state publishes new statewide counts on weekdays, and new county data once a week on Wednesdays. Last week, there was no update at all on May 19, and county data was instead updated on May 24. On days when the state total is updated but the county totals are not, the new cases are placed into the "unknown" county category.

**Comment by tiffehr** [comment]
We're very fortunately at the point where states have reduced the frequency of their updates, with states and county reporting occasionally separated like RI.  But it does introduce some gymnastics/complexity, as @lwaananenjones describes.
