### ISSUE TITLE
Data Issue:  

### ISSUE THREAD

**Issue by jepler** [nytimes/covid-19-data#593]
### Describe the issue:
- [X] Incorrect number of cases or deaths

### Fuller details
Many counties in Nebraska have had frozen case counts for approximately the past week (e.g., no change in Lancaster county since 2021-05-25 at least until 2021-05-31).  I wonder if this is a case similar to #560, where the county level data is simply not being made available in the right way any longer.

**Comment by tiffehr** [comment]
Yes, that's correct.  [Nebraska's DHS](https://dhhs.ne.gov/Pages/Coronavirus.aspx) dropped county-level figures for something more like health districts.  We are trying to figure out alternative data sources or if they'll restore the per-county figures.

**Comment by mikelehen** [comment]
@tiffehr Curious if you could provide an update.  I think I see some data coming through for at least some Nebraska counties, but I'm curious if this issue is fully resolved or you're still scrounging for reliable data?  Thanks!

**Comment by tiffehr** [comment]
@mikelehen We are working on patching in county-level sources, since the state has not seen fit to provide per-county since moving to their health-district map.  More coming soon, but I doubt it'll be the full set of Nebraska counties.  For some we may use CDC figures, which run behind but not as behind as NO data.

More on that soon.  (I'm working on Three Rivers HD's data as I type.)
