### ISSUE TITLE
Data Issue:  Wyoming cases not updating

### ISSUE THREAD

**Issue by ghop02** [nytimes/covid-19-data#594]
### Describe the issue:
- [x] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
It seems that the wyoming case series has stalled for the past few days.  Looks like the cases have increased a bit here https://sites.google.com/wyo.gov/covid-19/home - the latest value in your data is 60,144 but the number is higher on the wy dashboard
![image](https://user-images.githubusercontent.com/1422280/120518386-872cab00-c39f-11eb-850a-be1b07c0e460.png)

**Comment by tiffehr** [comment]
@ghop02 Our source for Wyoming's county data is [their public Tableau dashboard](https://public.tableau.com/views/EpiCOVIDtest/Dashboard?:embed=y&:showVizHome=no), which has not updated since 5/28.  

We expect they'll update it today at some point given past holiday patterns.  Since early March, Wyoming has only updated their data weekdays, Monday to Friday. They do not update on the weekends and a three-day weekend extends that lag.

![image](https://user-images.githubusercontent.com/60173/120528332-8fcdb300-c398-11eb-8e1f-d4101d1b97b0.png)

When there are multiple sources for a given locality, we choose only a few that have a record of strong methodological explanations and closeness to official sources that the health department uses in their reports. We are not currently using figures from WY's Google Sites page nor see the need (yet).

**Comment by ghop02** [comment]
Hi @tiffehr, I think they recently moved their dashboard and have a new link: 
[here's the current link](https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-state-and-county-dashboards/)
and I checked the [wayback machine on May 28th](https://web.archive.org/web/20210528073308/https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-state-and-county-dashboards/) and it does not reference a moved link.  My guess is that they made a new dashboard/tableau view

**Comment by tiffehr** [comment]
@ghop02 Ah, thanks.  We'll confirm the change is permanent and go extract stuff from the [new Tableau cases/deaths dashboard](https://public.tableau.com/views/WYCOVID-19Dashboard/WyomingCOVID-19CaseDashboard?%3Aembed=y&%3AshowVizHome=no).  May be done by end of day, and flow through accordingly tomorrow.

**Comment by ghop02** [comment]
thanks!
