### ISSUE TITLE
Data Issue:  Florida stops publishing daily COVID data

### ISSUE THREAD

**Issue by zshe3** [nytimes/covid-19-data#596]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [X] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
According to this [nytimes article](https://www.nytimes.com/2021/06/04/world/florida-covid-19-cases-vaccine.html), Florida will no longer publish daily coronavirus reports. In the past three days, [Florida's COVID data in this database](https://github.com/nytimes/covid-19-data/blob/master/us-states.csv) has been staying the same, i.e.

date,            state,   fips, cases, deaths
2021-06-05,Florida,12,2329859,36972
2021-06-04,Florida,12,2329859,36972
2021-06-03,Florida,12,2329859,36972.

However, this issue is not listed in the in the [anomalies.csv](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv) file.

**Comment by lwaananenjones** [comment]
Thank you for asking about this, and that's correct — Florida is only providing weekly data updates now, so the counts will stay the same until the next update (expected June 11). Although Florida is the first state to report so infrequently, there are several other states that report only MWF or only report county data weekly. Our [state tracker pages](https://www.nytimes.com/interactive/2021/us/florida-covid-cases.html) list update frequency under "About the Data," and we'll consider how to make that information more accessible here since infrequent reporting will likely become more common.

**Comment by zshe3** [comment]
Thank you for the clarification!
