### ISSUE TITLE
Data Issue: Cases in Collin County, Texas no longer being reported.

### ISSUE THREAD

**Issue by mikelehen** [nytimes/covid-19-data#597]
### Describe the issue:
- [X] Incorrect number of cases or deaths

### Fuller details
Collin County, TX seems to have stopped reporting updated case numbers.  They've been stalled at 75111 cases since 2021-05-28.

I'm not sure if there's an alternative source or other solution.  Barring that, should the CSV maybe have empty entries instead of continuing to report the same (stale) number so that it's apparent the data is no longer being reported?

For reference, the NYT visualization:
![image](https://user-images.githubusercontent.com/206364/121070490-a3579000-c783-11eb-82c0-5ecbe6c9efbc.png)

**Comment by mikelehen** [comment]
Note that https://experience.arcgis.com/experience/c00baf45f12a4899aae1c812e29d6cde says:

> Collin County will no longer post COVID-19 case data on this website. Counts of new and confirmed cases, those who have recovered, and COVID-related deaths in Collin County may be obtained from the Department of State Health Services at [this link](https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83).

But the linked dashboard is stalled at 75111 too.

**Comment by tiffehr** [comment]
We used the state's data for Collin County, TX:  https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83  It too is plateaued at `75,111`.
![image](https://user-images.githubusercontent.com/60173/121102731-9a82b080-c7bb-11eb-984a-16f0d02b3a6c.png)

Until the county reports an updated figure to the state, ours will match the state. Collin County discontinued their own dashboard back in August 2020, and we had no alternate data source at the time.

**Comment by tiffehr** [comment]
But to clarify the issue, we don't drop to zero, since our figures are _cumulative_ counts.  So they stay plateaued during lulls.  If you want empties, it's best to have a running diff calculation and handle the case where the diff is zero.  We specifically chose to not do nulls or zeros for geographies that are plateaued, because some actually behave this way within daily update cycles.

**Comment by mikelehen** [comment]
Thanks.  Yeah, I was thinking it would be nice to report nulls only in cases like this where a human has looked at it and determined that the data has artificially stalled.  That way consumers of the data (like https://www.nytimes.com/interactive/2021/us/collin-texas-covid-cases.html presumably) wouldn't trail off to zero erroneously.  But that only really makes sense if you have humans in the reporting loop already.  I don't actually know how the data is being collected and whether there's much/any human intervention normally.  In any case, thanks for taking a look!

**Comment by tiffehr** [comment]
@mikelehen It's worth recalling that our methodology here has been active and consistent for more than a year now, nearly 500 days.  We are not going to make big shifts within the long tail of the pandemic's ebb.  We do have humans in the reporting loop, doing manual data collection and a full review of each day's incoming figures, and strove for a public data set that satisfies the core needs of most.

Other users of this public data set have calculated the daily diff where needed.  Our choices support that, but we have not added that calculation into our data because folks expect different styles.  (Empty vs. null vs. zero vs. "empty", etc.)

**Comment by mikelehen** [comment]
@tiffehr Fair enough!  Thanks for the explanations! 😁
