### ISSUE TITLE
Data Issue: King County, WA

### ISSUE THREAD

**Issue by nick112blue** [nytimes/covid-19-data#598]
### Describe the issue:
- [ ] Incorrect number of cases or deaths

There seems to be a huge discrepancy in cases and deaths. NY Times is reporting 40 deaths in King County over the past 14 days. King County is reporting 14. 

On June 9th NY Times reported 1230 cases. That’s more than the entire state for several days combined. Also King County reported nothing close to those numbers on that day. 

https://public.tableau.com/views/PHSKCOverviewDashboard/Overview?%20:embed=y&:toolbar=n&:display_count=n&:showShareOptions=n&:showVizHome=n

https://www.nytimes.com/interactive/2021/us/king-washington-covid-cases.html

**Comment by lwaananenjones** [comment]
Our data for King County is currently from the state health department. We've noticed the fluctuations this week, including both a large decrease and a large increase, but haven't yet heard back from the state about an explanation. 

We count each day's total based on the difference of the cumulative counts from day to day, so that's often different from how states and counties report based on date of death or another metric. But in this case we do plan to either revise the data or add an anomaly note once we have more information.

**Comment by tiffehr** [comment]
King County's figures should be in a better place tomorrow, once we revise our options.
