### ISSUE TITLE
NYC fips value is null

### ISSUE THREAD

**Issue by rpsoko** [nytimes/covid-19-data#6]
This may be intentional/an artifcat of how data is collected, but why does NYC have a null fips value?

I've brought this dataset, along with other covid datasets into BigQuery for comparative analyses purposes. Here's the query, and I've verified the raw CSV file is also missing a value for NYC

![Annotation 2020-03-27 104155](https://user-images.githubusercontent.com/993431/77767528-984d8f80-7017-11ea-8331-5a94283726c3.png)

This is the resulting visualization as a result (using Tableau):
![Annotation 2020-03-27 104021](https://user-images.githubusercontent.com/993431/77767386-5fadb600-7017-11ea-97c6-b3d185ba7d4d.png)

**Comment by rpsoko** [comment]
In case anyone else is doing what I'm doing, I have the following workaround using a Tableau calculated field.

![Annotation 2020-03-27 105413](https://user-images.githubusercontent.com/993431/77768755-4e65a900-7019-11ea-8f74-93ed3eec6243.png)

**Comment by albertsun** [comment]
Hi, yes, it's intentional. We report a single value for New York City, encompassing all five boroughs. The FIPS code 36061 is only for New York County (Manhattan). If you are mapping like that you should apply the value for "New York City" to geographies for the FIPS codes for New York, Kings, Queens, Bronx and Richmond counties together.

**Comment by rpsoko** [comment]
Great, thank you
