### ISSUE TITLE
Harris County, TX -  Many days of 'negative' cases

### ISSUE THREAD

**Issue by MirrorCola** [nytimes/covid-19-data#603]
Do you have any info regarding what's going on here?

Both the city of Houston and Harris County have many days over the last few weeks where the cumulative new cases have decreased.  I can find no information locally, so I just wondered if your sources gave you any explanation (I have my own guesses, but...)

Not urgent, but useful.  Thank you

**Comment by lwaananenjones** [comment]
For Harris County, we collect data each day from both the county and the state. The state often has notes with a little information, such as this one on June 17:

> A large decrease in Harris County confirmed cases due to deduplication was included in cumulative totals but not new confirmed cases for today.

We've seen similar large decreases in other Texas counties recently, so it's likely there is an ongoing audit of case records to identify duplicates or move cases to the correct county based on location of residence. Decreases have been more common in the past month or so across many states, and I think that's a combination of health departments having more time to audit records now that new cases are lower in most places, and because there are fewer new cases to outweigh the removals.

**Comment by tiffehr** [comment]
@MirrorCola I hope that helps!  Close this Issue, if so?  (We're also happy to answer follow-up questions, though the inner workings of Harris County's health department are of course a bit beyond our expertise.)

**Comment by MirrorCola** [comment]
Thank you for your efforts throughout and quick response, that does help.  Please go ahead and close this issue.
