### ISSUE TITLE
Data Issue:  Florida deaths after 10 June 2021?

### ISSUE THREAD

**Issue by tanimislam** [nytimes/covid-19-data#612]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [x] Other

### Fuller information
Apologies for mangling the template. I have noticed that there are no recorded COVID-19 deaths after 10 June 2021 in The NY Times COVID database. Best illustration I could provide is this MP4 file I prepared, [COVID-19 7-day rolling average of new cases and deaths per day in Florida](https://tanimislam.sfo3.digitaloceanspaces.com/covid19movies/covid19_7day_florida_LATEST.mp4).

I ask here because I could find no mention of this or similar issue when searching on "Florida" for GitHub issues in this repo.

**Comment by lwaananenjones** [comment]
When Florida removed its dashboard and switched to a weekly report at the end of May, the state also stopped reporting deaths by county. The state has continued to report new deaths at the state level, which are included in our data for Florida and in the "Unknown" subgeography category. 

We're working on ways to more clearly signal when data is no longer available from any source, since this will inevitably become more common. Florida and Nebraska are currently the only states that do not provide county-level information about deaths. 

The [CDC maintains a separate county-level dataset based on death certificates](https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-in-the-United-St/kn79-hsxy), which may be useful. It is not directly comparable to our dataset or data published by most states because deaths are included based on where the death occurred rather than where the person lived.
