### ISSUE TITLE
Data Issue:  - Missing data for St. Clair County, Illinois in the US Counties datafile

### ISSUE THREAD

**Issue by AZIQB** [nytimes/covid-19-data#614]
### Describe the issue:
 Missing data for a locality
I have been noticing that data for St. Clair County Illinois is reported weekly and not daily - that leads to huge spike in our daily monitoring. 
We found out that the St. Clair County Illinois has been reporting cases daily. So why is no data. We started noticing this pattern since Jun 13 2021.
Thank you

**Comment by lwaananenjones** [comment]
Thank you for bringing this up. We use data from the county health department for St. Clair, Illinois, since local officials have consistently reported ahead of the state. In mid-June the county moved to a weekly reporting schedule, but I do see where they're now providing daily updates on Facebook again. We'll get those updates incorporated going forward.
