### ISSUE TITLE
Data missing - New York City as of 8/9/2021

### ISSUE THREAD

**Issue by avi123** [nytimes/covid-19-data#615]

**Comment by albertsun** [comment]
Hi @avi123 the NYC health department didn't report any data the last two days due to technical difficulties. We report on these issues in a file of anomalies here https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv#L763 and on our pages directly here https://www.nytimes.com/interactive/2021/us/new-york-city-new-york-covid-cases.html

**Comment by avi123** [comment]
@albertsun thank you!
