### ISSUE TITLE
Data Issue:  Can't reconcile KY data

### ISSUE THREAD

**Issue by rush70** [nytimes/covid-19-data#618]
### Describe the issue:
- [ X] Incorrect number of cases or deaths

### Fuller details

official counts from https://govstatus.egov.com/kycovid19 daily report

Date | Total Cases | New Cases | false positives removed | Sanity Check:  Previous Day Total Cases = Total Cases – New Cases + false positives removed
-- | -- | -- | -- | --
08/13/21 | 512224 |   |   |  
08/14/21 | 514621 | 2398 | 1 | 512224
08/15/21 | 516901 | 2280 | 0 | 514621
08/16/21 | 518987 | 2100 | 14 | 516901
08/17/21 | 522209 | 3276 | 54 | 518987

KY data from the NYT (us-states.csv):

date | state | fips | cases | deaths | New Cases = cases – previous day’s cases
-- | -- | -- | -- | -- | --
2021-08-10 | Kentucky | 21 | 503875 | 7454 |  
2021-08-11 | Kentucky | 21 | 506902 | 7467 | 3027
2021-08-12 | Kentucky | 21 | 509516 | 7472 | 2614
2021-08-13 | Kentucky | 21 | 513402 | 7485 | 3886
2021-08-14 | Kentucky | 21 | 513566 | 7486 | 164
2021-08-15 | Kentucky | 21 | 513698 | 7486 | 132
2021-08-16 | Kentucky | 21 | 520349 | 7504 | 6651

**Can't figure out how to reconcile.  Suspect data error.**

Also note, the data set linked to by JHU https://kygeonet.maps.arcgis.com/apps/opsdashboard/index.html#/543ac64bc40445918cf8bc34dc40e334 appears to match the KY official data.  Not sure where the NYT data is coming from.

###

**Comment by lwaananenjones** [comment]
Thanks for asking about this. We use the same daily report and Esri dashboard sources. There are a couple of reasons our data won't quite match what the state is publishing for daily counts, though the cumulative counts should be very similar:

1) The state doesn't provide updates on weekends, and then retroactively posts weekend reports on Mondays. Since our methodology is including cases and deaths on the date they are announced, we include the weekend update on Mondays when it's announced. (We do revisions of past data occasionally, such as for correcting errors, but we don't do this when it's part of a state's routine reporting pattern.)

2) We use a combination of state and local data for Kentucky and many other states. Several Kentucky health districts continue to report ahead of the state health department, so some cases are included from local sources several days before the state data catches up. An example is [Northern Kentucky Health Department](https://nkyhealth.org/individual-or-family/health-alerts/coronavirus/).

**Comment by tiffehr** [comment]
@rush70 I'm going to close this ticket, but do feel free to ask follow-up questions on it.  We'll respond as needed.

**Comment by rush70** [comment]
Q: When aggregating from multiple sources (as in case (2) above, NKY regional Health Dept. and KY daily reports), how do you avoid double counting?

Thanks.

**Comment by tiffehr** [comment]
@rush70 We pick between them, based on clearest methodology and speed. Or even responsiveness, from the local HD officials. We don't sum.

**Comment by lwaananenjones** [comment]
Here's an example with recent data for Boone County:

  | Local district | State | NYT
-- | -- | -- | --
2021-08-10 | 15,554 | 15,242 | 15,554
2021-08-11 | 15,613 | 15,301 | 15,613
2021-08-12 | 15,667 | 15,347 | 15,667
2021-08-13 | 15,754 | 15,437 | 15,754
2021-08-14 | no update | no update | 15,754
2021-08-15 | no update | no update | 15,754
2021-08-16 | 15,899 | 15,541 | 15,899
2021-08-17 | 15,966 | 15,605 | 15,966


The default logic is that the higher number is the most up-to-date, but there are instances where we choose the lower number instead, such as when a county announces they removed cases after auditing records and removing duplicates.

**Comment by rush70** [comment]
Makes sense.  Thank you for the clarifying example.
