### ISSUE TITLE
Data Issue:  Data mismatch when compared to CDC stats

### ISSUE THREAD

**Issue by MehraSakshi** [nytimes/covid-19-data#624]
### Describe the issue:
- [ ] Missing time-series information
- [ ] Data reported on CDC website does not match the numbers on NYTimes
Sources
CDC : https://covid.cdc.gov/covid-data-tracker/#trends_dailycases
NYT : https://www.nytimes.com/interactive/2021/us/florida-covid-cases.html

### Fuller details
Data updated on CDC (i.e reported date of cases ) is a day prior to NYT (i.e announced date of cases).

As per NYT, the reported count on 6th Sept is zero because many jurisdictions did not announce new data on Labor Day and the accumulated data(56082) is updated on 7th September.

Is it possible to eliminate the discrepancy in daily reported case information in accordance with CDC data table 'Data Table for Daily Case Trends - Florida'

**Comment by lwaananenjones** [comment]
This is correct, there are slight methodology differences between our data and the CDC's data. In most states we don't use CDC data as a source, but for Florida we do use the cumulative counts the state reports to the CDC between the state's own weekly update on Fridays. 

The CDC labels each day's data with the previous day's date, such as reporting data from Sept. 8 on Sept. 9. Our methodology is to always include cases and deaths on the date they're announced, as you mention. We always use cumulative counts rather than stated "new" cases because there are different methods for calculating new cases, and we don't retroactively adjust previous days' totals unless necessary to correct errors. The hope is that this consistency allows our data users to choose their own smoothing or averaging methods for days when jurisdictions don't announce new data.

**Comment by jnedum** [comment]
Looking at Sep 7 cumulative totals for the US is far off other sources like CDC, WashingtonPost, and WorldOMeter.  You show 301k cases, which would be an all-time daily high in the US (according to your chart).  But the other sources are not showing anything close.

**Comment by lwaananenjones** [comment]
The Sept. 7 total includes many cases from the preceding three days since many jurisdictions do not report new data on weekends or holidays (Labor Day), so while it was the largest number of cases reported on a single day, it shouldn't be interpreted as a one-day total. The rolling average is better for comparing trends over time. 

Our daily count of new cases is based on the difference in the cumulative total from one day to the next, based on how many cases and deaths have been announced at that point. For example, the [cumulative cases count](https://github.com/nytimes/covid-19-data/blob/master/us.csv) was 40,082,242 on Sept. 6 and 40,383,380 on Sept. 7, for a difference of 301,138 cases. For comparing across sources, it is often more useful to compare the cumulative counts since there are different ways of allocating "new" cases per day, especially since there may be different ways of handling the holiday interruptions.
