### ISSUE TITLE
Vaccination Data for Coconino County is inaccurate 

### ISSUE THREAD

**Issue by csedwar** [nytimes/covid-19-data#638]
The data reported on vaccination rates (and possibly others) on NYTimes does not align with that reported by the county. 

See: https://coconino.az.gov/DocumentCenter/View/47415/Coconino-County-COVID-19-Weekly-Update--Week-42

**Comment by tiffehr** [comment]
Our primary source for vaccination data is the [CDC's public data set](https://covid.cdc.gov/covid-data-tracker/#county-view|Arizona|4005|Risk|community_transmission_level).  We do not use local sources in Arizona, since they have matched figures reported to the CDC with decent speed.  This may be a lull in CDC's processing from that county.

![image](https://user-images.githubusercontent.com/60173/140092452-2b12e127-2aab-490f-9e33-8eeed0b3be04.png)

The Week 42 PDF you shared seems to be a bit behind:  10/17–10/23, showing `Total Fully Vaccinated: 73,023 (59.7% of the eligible population)`.  The CDC's figures match the Vaccine Data available from the county (but not in that PDF).

![image](https://user-images.githubusercontent.com/60173/140094251-700e8cbe-5ca2-4f53-8a18-ee29f2c03210.png)

CDC is still ahead of either the county or the PDF.

**Comment by tiffehr** [comment]
@csedwar Please re-open this if I have misunderstood what you wanted us to do?

**Comment by csedwar** [comment]
@tiffehr thanks very much for the clarification! I will follow up with the county to figure out why their PDF is so behind. Much appreciated.

**Comment by tiffehr** [comment]
@csedwar I think the PDF is only a weekly publication, compared to that live Vaccine Data page.

**Comment by csedwar** [comment]
@tiffehr Yeah I agree. I am just skeptical that the differences reported on the Coconino website vs CDC are accounted for.  The Coconino website says (as you posted) 74,663 fully vaccinated, whereas CDC says 98,569.  The county page says it was updated today, so at least for the websites they appear to not be lagging. 

Perhaps the reason for the delta is those who live in coconino but were administered a vaccine elsewhere in the state, which may get rolled up in the state/CDC totals.

**Comment by tiffehr** [comment]
CDC's footnotes indicate that they strive to show county figures by county of residence, not dose(s) administration.
![image](https://user-images.githubusercontent.com/60173/140231133-89f88013-5cc3-45fc-ada4-6996637c5424.png)  

Coconino's Tableau dashboard with the `89,957` tally matches the [State's own dashboard](https://www.azdhs.gov/covid19/data/index.php#vaccine-admin), which shows `89,957` BUT only on the tab of County by Administration. (County by Residence for Coconino is `87,171`, to add a FOURTH number to the mess.)

![image](https://user-images.githubusercontent.com/60173/140231974-65c3b97a-b370-4ff0-89a3-3bef8a71b8a9.png)
