### ISSUE TITLE
Florida, RI, North Carolina not reporting new cases for a week

### ISSUE THREAD

**Issue by Paracutin1** [nytimes/covid-19-data#644]

**Comment by lwaananenjones** [comment]
About 20 states did not report new data for four days for the Thanksgiving holiday, from Nov. 25-28. Rhode Island and North Carolina were in that group, but have returned to their standard reporting schedules. Florida typically issues a weekly report on Fridays; the Nov. 26 report was instead released on Nov. 30 because of the holiday.
