### ISSUE TITLE
Question:  COVID-19 variant data as reported in NYC

### ISSUE THREAD

**Issue by brent-williams** [nytimes/covid-19-data#646]
The NYC front page 2021-12-10 'Where has Omicron been detected' shows a map w/ Omicron data.  

I'm unable to find any variant-related data in this repo.

Can you advise where I might find the variant-related data that was used to produce the map?

I've checked README and FAQ, no luck.

Thanks for a great resource and making it publicly accessible.

**Comment by tiffehr** [comment]
We have no variant-related data in this repository, and do not plan to add it since the variant type and distribution information changes quickly and is often revised as definitions change.  Our map notes at the bottom that some of our data comes from the Centers for Disease Control and Prevention and GISAID, for SARS-CoV-2 lineages.  (I'll ask specifically how much of our map may be based on reporting from those sources but my Impression is it's a mix plus our own reporting.)
