### ISSUE TITLE
Data Issue:  Maryland reports no new cases since December 5

### ISSUE THREAD

**Issue by eguidotti** [nytimes/covid-19-data#649]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [x] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
Maryland reports no new cases since December 5. They are fixed to `cases=592912` and `deaths=11255`. Same problem for Maryland counties. See also https://github.com/covid19datahub/COVID19/issues/186#issuecomment-994204871 and https://github.com/covid19datahub/COVID19/issues/187#issuecomment-994203562

**Comment by tiffehr** [comment]
We know about the lull [due to the cyberattack on Maryland's health department](https://www.baltimoresun.com/coronavirus/bs-md-maryland-health-department-covid-data-cyberattack-20211213-d6t2fqiisffpte7xmuzxm5dudi-story.html) but have no alternative data sources.  We're will grab new figures as soon as they're able to publish, and will consider a historical revision if that data is available.  If not, we will mark their spike of catch-up case counts as an anomaly with the usual notes

**Comment by eguidotti** [comment]
Thanks a lot for your quick reply!
