### ISSUE TITLE
Data Issue: Reynolds County, MO

### ISSUE THREAD

**Issue by chris-prener** [nytimes/covid-19-data#650]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [X] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The NYTimes latest map/case count shows no data for Reynolds County, Missouri in the last week. DHSS's dashboard does show cases have been reported, however. Thanks for looking into this and for all you do to keep collecting these data!

**Comment by lwaananenjones** [comment]
Thank you for bringing this up — this is an instance where we've used the county's data for a long time because the county has been reporting ahead of the state, but recently the county stopped reporting any new data. Once we confirm this is permanent, rather than something like a temporary decision based on low staffing, we'll take steps to convert the county to the state data source. It should happen this week.

**Comment by chris-prener** [comment]
Great thanks @lwaananenjones - I believe this is part of the trend of local health departments stepping back from data reporting after a judge's order last month.
