### ISSUE TITLE
Data Issue:  Cases shown on December 25th are incorrect for UK.

### ISSUE THREAD

**Issue by Saurabh0027** [nytimes/covid-19-data#651]
The source is found to be Github New cases for 25th Dec is 0.

And, as per the announcement over Github the data for 24th and 25th Dec, was supposed to update on 27th Dec, as per source.

Now, on the Official Website, the data for daily confirmed cases for 25th Dec 113,628. 

https://coronavirus.data.gov.uk/details/cases?areaType=nation&areaName=England
and for 24th Dec is 105,069. 

So as per the above official data, the number of new cases on 25th Dec is found to be 8559.

Kindly look into this and resolve the issue.

**Comment by tiffehr** [comment]
@Saurabh0027 Do you mean our data here in this repository, "as per source"?  Or do you mean another GitHub repository's public data set?  I'm struggling to understand which figures come from our data here vs. another possible source.

**Comment by Saurabh0027** [comment]
@tiffehr i am referring to your data repository not any public data set.

**Comment by tiffehr** [comment]
Thank you.  What you see on the 25th reflects our ongoing methodology:  reporting cases _on the day they're reported_, rather than chasing revision histories as health departments backfill in (weekend) gaps.  That means we have zeros for days when no new data was reported, which may not match a chronological data set from the source that they revise after the fact.  Our focus is the current tally, which is still correct in either case.
