### ISSUE TITLE
Data Issue:  Missing/Not Updated Maryland County Level Data December 4 through 28, Dec-30 to Jan-2

### ISSUE THREAD

**Issue by brianmcentire** [nytimes/covid-19-data#656]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Maryland Department of Health experienced a network or server outage for most of December 2021. Beginning December 4 through December and again the numbers did not change from December 30 until January 2, 2022

Will the data be corrected in https://github.com/nytimes/covid-19-data/blob/master/us-counties.csv ?

Here is an one example statement on the Maryland Department of Health Coronavirus website acknowledging the event and data outage:  "12/16/2021: MDH is experiencing a server outage. Hospitalizations data are current. Other surveillance data will be updated as soon as possible."
https://web.archive.org/web/20211216173917/https://coronavirus.maryland.gov/

**Comment by lwaananenjones** [comment]
At this point we don't have immediate plans to revise Maryland's December data since we don't have enough information from the state to allocate those cases and deaths in a way that's consistent with our methodology. Our data includes cases on the date they're added to the cumulative total. The state has a time series of cases by day at the state level that we've been looking into.

We monitored this at the time and have the dates documented in our anomalies.csv file, which is part of our [rolling averages dataset](https://github.com/nytimes/covid-19-data/tree/master/rolling-averages). The lull from Dec. 30 to Jan. 2 is because the state took several days off for the New Year's holiday, so that was more typical. Maryland has rarely taken holiday breaks, but many other states do.
