### ISSUE TITLE
Data Issue:  San Mateo county :- Suspicious number of new cases on 10 Jan 2022.

### ISSUE THREAD

**Issue by gauravjoshijo** [nytimes/covid-19-data#658]
San Mateo county new cases(5949) on 10 Jan 2022 seem suspicious when compared to below given sources.

[Usafacts.org](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/state/california/county/san-mateo-county) : New cases on 10 Jan 2022:--> 1967
[Covid19.ca.gov](https://covid19.ca.gov/state-dashboard/#county-statewide): : New cases on 10 Jan 2022:--> 1950
[smchealth.org](https://www.smchealth.org/data-dashboard/county-data-dashboard): : New cases on 10 Jan 2022:--> 1978

Please look into this and confirm if the data is correct or not.

**Comment by lwaananenjones** [comment]
Thank you for asking about this. Our data includes cases on the date sources add them to the cumulative total, with new cases calculated from the daily change in cumulative cases. The large number of cases added on Jan. 10 represents three days of data since the state doesn't update its counts on the weekends. The rolling average accounts for those days with no new data. The state and county dashboards allocate cases by "episode date," meaning the date someone is tested or diagnosed.
