### ISSUE TITLE
Data Issue:  US death count decrease for 2022-03-14

### ISSUE THREAD

**Issue by amdilley** [nytimes/covid-19-data#664]
### Describe the issue:
- [ ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths

### Fuller details
US death totals for 2022-03-13 is 966361 and the US death totals for 2022-03-14 is 963926 is us.csv. Is this supposed to be 966926? Otherwise earlier death counts need to be corrected.

**Comment by albertsun** [comment]
Hi @amdilley this is because Massachusetts retroactively revised their number of deaths, as noted in our list of data anomalies here: https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv#L1504

The data we maintain is based on reporting date, so for a change like this that results in a declining count we do not revise past deaths counts.
