### ISSUE TITLE
Data Issue:  Suspicious number of cases | Nevada, USA

### ISSUE THREAD

**Issue by nickybisht** [nytimes/covid-19-data#670]
Incorrect number of cases or deaths
- As per check there is a huge data difference found between [source NYT feed](https://github.com/nytimes/covid-19-data/blob/master/us-states.csv) and other official sources like Worldometer and CDC for daily new cases count on 15th March 2022 for location Nevada, USA.
- New york times  Feed- 22655

- [Worldometer](https://www.worldometers.info/coronavirus/usa/nevada/) - 127

- [CDC](https://covid.cdc.gov/covid-data-tracker/?CDC_AA_refVal=https%3A%2F%2Fwww.cdc.gov%2Fcoronavirus%2F2019-ncov%2Fcases-in-us.html#trends_dailycases) - 0

Please look into this data discrepancy as here is a huge difference between the stats.

**Comment by tiffehr** [comment]
Thank you for writing in.  I think the difference you see is methodological.  NYT takes data from our sources -- mostly state and county health departments -- using the date the cases were reported.  Some locations do report backlogs, which was the case in Nevada in March.  

In those cases, we mark the increases as an anomaly and exclude it from our calculations, like the rolling averages.
![image](https://user-images.githubusercontent.com/60173/161602151-fbfebb5c-6e0f-422b-8311-c2f9ada5e157.png)

We have an entry about anomalies [in this file](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages/anomalies.csv#L1512-L1524) which we encourage public data-set users to study.  It includes the Nevada backlog you noted, with our decisions about if we keep/omit the data.

Those also appear on our relevant pages:
![image](https://user-images.githubusercontent.com/60173/161602414-82b74dab-7525-4e6e-aeeb-d4b0f529728c.png)

Worldometer and/or the CDC either smoothed out the backlog into historical changes or simply did not include all the cases announced that day.  Their choices are up to them, of course.  We do not try to match their data, in order to keep our own methodology consistent for users.
