### ISSUE TITLE
Data Issue: Daily cases and daily death cases of 16th Feb, 2022 seem incorrect. 

### ISSUE THREAD

**Issue by gauravjoshijo** [nytimes/covid-19-data#672]
### Describe the issue:
- [ ] Incorrect number of cases or deaths

### Fuller details
As per the [NYT feed](https://github.com/nytimes/covid-19-data/blob/master/us.csv), daily cases and daily death cases of 16th Feb, 2022 were 141,180 and 3306 respectively.

Whereas on other sources of 16th feb:

[WHO](https://covid19.who.int/region/amro/country/us)- 
Daily cases- 173,247
Daily death cases- 2911
[Worldometer](https://www.worldometers.info/coronavirus/country/us/#graph-cases-daily) - 
Daily cases- 117,576
Daily death cases- 2915

Please look into this as there seem a data discrepancy in the feed. 

Thanks you

**Comment by albertsun** [comment]
Hi @gauravjoshijo our data methodology is laid out in the README and in this FAQ and is derived from a reported date count based on data from state and county health departments. Other sources use differing methodologies that differ from our counts because of the differing methodology. We would not expect every day's count to be exactly the same between all sources.
