### ISSUE TITLE
counties.csv hasn't updated in 3 days  

### ISSUE THREAD

**Issue by mjwebster** [nytimes/covid-19-data#677]
### Describe the issue:
Last update on the counties.csv file seems to be 5/13/22, which is 3 days ago.  Other files appear to have been updated earlier this morning.

**Comment by tiffehr** [comment]
Howdy, @mjwebster!  Fan of your work.  😄 
We've run into a limit with GitHub's raw file uploads.

> This file is now updating. For anyone following along, the original us-counties.csv file is now almost at or over the Github file limit and will soon stop updating.
_Originally posted by @albertsun in https://github.com/nytimes/covid-19-data/issues/674#issuecomment-1123957366_

We're recommending people use the year-based county files from now on.

**Comment by mjwebster** [comment]
Thank you @tiffehr ! I was wondering if you guys might hit that at some point. It certainly is a lot of data.

**Comment by albertsun** [comment]
@bdklahn we wouldn't do that because the new file is not of the same format as it does not contain the whole history of the file.

Unfortunately we think in this case it's best for people to manually see the change and update any processes they are running using the data to use the new format.

**Comment by bdklahn** [comment]
I understand.
But the update already changes the fundamental format of that file to no longer contain the whole history to date.
So, I wondered, since the fundamental format was already changed, if another version of fundamental change might be less disruptive for folks.
If folks need older data, they can always go back to a previous git snapshot to pull that big file, or whatever.

Anyway, I can pretty easily adjust local scripts, etc. I just wondered . . .

Simple file names like us-counties.csv (v.s., say, something like  us-countiies-YYYY-MM-DD.csv) are often inferred by people to mean "current data".
Anyway all this COVID time series data stuff . . . is hard to snapshot, anyway, given "backfill" updates which change "history".

So I appreciate any of this data wrangling effort you folks are already doing.

We'll deal with it.

Thank you!

**Comment by gwillen** [comment]
It looks like this caused the Google Cloud "New York Times US Coronavirus Database" dataset to stop updating at the same time: https://console.cloud.google.com/marketplace/product/the-new-york-times/covid19_us_cases

That page says it's based on the data in this repo, but I don't know who maintains it -- is it possible to get it updating again? A tool I use, covid-19.direct, has stopped updating in turn from the Google Cloud dataset.

Thanks!

**Comment by tiffehr** [comment]
@gwillen We don't know who owns that (but it's fun to see it listed and use it in BigQuery's SQL workspace).

**Comment by gwillen** [comment]
> @gwillen We don't know who owns that (but it's fun to see it listed and use it in BigQuery's SQL workspace).
> 
> Update: based on the Marketplace page, looks like Google runs it in order to promote BQ.
> 
> ```
> https://mail.google.com/mail/u/0/?view=cm&fs=1&to=public-data-help@google.com&su=Public%20Datasets%20Issue:%20[INSERT%20ISSUE%20SUBJECT%20HERE]....
> ```
> 
> I'll ping that email and see who responds.

Thanks very much!! I greatly appreciate your help.
