### ISSUE TITLE
Data Issue:  Huge difference between NYT & CDC daily new cases for US

### ISSUE THREAD

**Issue by nickybisht** [nytimes/covid-19-data#680]
Date | [NYT](https://github.com/nytimes/covid-19-data/blob/master/us.csv) | JHU | [Govt. website (CDC)](https://covid.cdc.gov/covid-data-tracker/#trends_dailycases)
-- | -- | -- | --
19th June 2022 | 14607 | 21207 | 39896
20th June 2022 | 54196 | 43310 | 56535
21st June 2022 | 209738 | 119110 | 185237

As visible for these 3 dates, the stats in NYT is comparatively very less than the CDC stats. 
![image](https://user-images.githubusercontent.com/90417853/175321649-846d5e65-8c4d-4864-b7f8-e12760012f97.png)

**Comment by tiffehr** [comment]
Thank you for your question.  We have aspired to address [methodological questions in our README](https://github.com/nytimes/covid-19-data#methodology-and-definitions), but the main reason is that there are slight differences in definitions between our data, JHU and the CDC. In most states we don't use CDC data as a source but rather the local or state health department reporting.  Also, the CDC labels each day's data with the previous day's date, such as reporting data from June 8 on June 9. 

Our methodology is to take cases/deaths on the date they're announced publicly. We use _cumulative_ count increases rather than reported "new" cases per location because there are different definitions across different sources.  We don't retroactively revise previous totals unless necessary to correct errors.  We do not strive to match external sources, given all those shifting definitions.
