### ISSUE TITLE
Data Issue: Missing Cases Data in Jefferson County, KY (FIPS: 21111)

### ISSUE THREAD

**Issue by mikelehen** [nytimes/covid-19-data#698]
### Describe the issue:
- [X] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [X] Missing data for a locality
- [X] Missing time-series information
- [ ] Other

### Fuller details
Case data for Jefferson County, KY (fips 21111) appears to stop December 25th. Data for other counties in Kentucky continues to be reported. A quick google search in the news does not show anything that would easily explain the discrepancy.  Not sure if it's helpful, but there was a previous issue for Jefferson County reported in #692.

![image](https://user-images.githubusercontent.com/206364/211687959-db0e68df-c607-4c10-b066-3884e1ac7d6b.png)

That data, at least in weekly form, continues to be shown at the CDC Covid Tracker site.
![image](https://user-images.githubusercontent.com/206364/211688131-b8512ea9-eccd-402b-a18a-b5c098fd99e5.png)

**Comment by tiffehr** [comment]
#692 reports what we know. The county is no longer reporting data to the public but we expected they would continue reporting weekly through the [state's dashboard](https://govstatus.egov.com/ky-covid-data-dashboard).  The state last showed an update in Jefferson County on 01/03/2023 (an update where the county's figures went _backward_, from 278,467 down to 277,221).   The state dashboard only updates once a week -- usually Mondays -- so that's contributing to the seeming delay.

That continues to leave us with 0 new reported cases since the last change to the county's cumulative cases, as our chart shows. 

It's unclear what CDC's data source is, if not the state report.  They could be using a separate data point from Kentucky that just shows weekly new cases, which we have never collected.  Since we can't see their cumulative count increasing, it's hard to say it's a standalone data point.  (We do not try to match other organization's numbers, due to differences in methodology and the structure of our database.)

**Comment by mikelehen** [comment]
@tiffehr Thanks very much for the detailed update! That's very helpful. I guess we will continue to monitor for now. 🤷

**Comment by mikelehen** [comment]
To fully close the loop, it looks like data is flowing again.  Thank you! 🙏 

![image](https://user-images.githubusercontent.com/206364/214363654-e880fc43-e4e8-4348-9e84-5c877fc74a74.png)
