### ISSUE TITLE
Can you add a column for "recovered"?

### ISSUE THREAD

**Issue by MntGoat76** [nytimes/covid-19-data#93]
Showing the growth of people recovered relative to new cases can give people hope.
I realize this isn't a small task but I think it would help a lot of people.
(Yes, the quality of the data could be an issue, but the John Hopkins ArcGIS site used to track and display this information)

**Comment by ddlatham** [comment]
Yes, please! (Or alternatively, an active cases column)

**Comment by sdetweil** [comment]
would be nice to have, extend charting

**Comment by ander909** [comment]
This would be a valuable addition! I would appreciate this addition! Thanks!

**Comment by Cryowatt** [comment]
If someone could link a source for this data, that would be great. As far as I can tell it either doesn't exist or it's being suppressed.

**Comment by albertsun** [comment]
Unfortunately, we aren't able to.

For this data release we focused on consistent, nationwide county-level data for cases and deaths. Most other data about Covid-19 is not available consistently at the county level.

Recovered cases (or the flip side, active cases) in particular is difficult because most health systems are not following up with people who have tested positive to see if they have recovered.

There are other efforts out there to collect more types of data, which we hope will improve over time.

**Comment by LarryTubbs** [comment]
Can we assume that if they don't die after a period of time, they must have recovered?  At some point the number of "active" cases will diverge from the total number of reported cases.  Only active cases put a burden on the health care system.

**Comment by jdkromkowski** [comment]
"Recoved" seems to be here with the caveats of definitional problems. https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data

**Comment by LarryTubbs** [comment]
Thanks!

-Lar
